### ISSUE TITLE
指定ユーザが、指定組織のメンバかリーダか判断する Add-on

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#1]
以下の仕様の Add-on を作成する。

設定項目

- I1. 対象ユーザ（ユーザ型データ項目で指定） 
- I2. 対象組織（組織型データ項目で指定）
- O1. 結果を保存する文字型データ項目

I1 が I2 のリーダであれば O1 に "L" を、メンバであれば O1 に "M" を、所属していなければ O1 に空を設定する。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

マージしましたが、以下、指摘です。

result と temp のように、グローバル変数はあまり使わない方が良いです。
その辺が解りやすくなるよう、スクリプト全体の構造を以下の形にしましょうか。

```javascript
main();

function main() {
  ...
}

function check() {
  ...
}
```

あと私なら check() 関数は以下のようにするでしょうか。

- リーダ／メンバのチェックのどちらをチェックするかを示す true / false の引数を渡す
- 関数内で検索をする
- 該当するかどうかの boolean 値を戻り値として返す

色々な形があると思うので、こうしなければならない、とは思いません。
が、リストを関数に渡すのは、「今一つだなあ」と思いました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

コードとしては最後ですかね。

user と group もグローバル変数である必要はないので、ローカル変数に変えましょう。

**Comment by hatanaka-akihiro** [comment]
@nishioka-q 

このアドオンの動作確認をお願いします。

設定項目のラベルや説明についても、レビューをお願いします。日英、両方とも。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

マージしてしまったんだけど、これ（以下）で見ると、またインデントがおかしくなってない？
タブ文字を使っている？

https://raw.githubusercontent.com/Questetra/Addon-XML/master/userCheck.xml


あと以下のサイトを活用しつつ、アイコンも設定するようにしてください。

https://yamamoto-q.github.io/Addon-XML-Image-Maker/dist/index.html

**Comment by chica-non** [comment]
userCheck.xmlについて確認しました。
アドオンを保存しようとするとエラーになります。
・インデントがおかしい
・; が抜けているところがある
できれば、軽く動かしてからテストに回してほしいです。
エラーを修正して、実行すると問題なく動作します。

もう少し、設定項目を親切にしてもいいかもしれません。
例えば、
ユーザデータのところにユーザ型データをセットしてください、とか、結果出力先もぱっと見では単一行なのか、複数行なのかわからないので、説明してもいいかもしれません。
以下の文ですが、he の前にthe はいるのでしょうか？
If the he or she is one of the members of the group,it returns "M".

**Comment by R-Matsubayashi** [comment]
>インデント
確かにおかしいですね。これで直ったと思います。
>; が抜けているところがある
チェック漏れでした。修正しました。
>エラー
こちらで試したところ、修正なしで保存・実行可能だったのですが……エラーはどこに出ていたのでしょうか？
>設定項目の説明
追記してみました。
>以下の文ですが、he の前にthe はいるのでしょうか？
不要ですね。修正しました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi @chica-non 

２人で挙動が違っている場合は、何かが違っているはず。
まったく同じ条件で同じことをして、違う症状になる可能性は低いです。（今回の事象を聞く限り、「たまたま」ということは無いと思います）

したがって何が違っているのか、相手に明らかになるような情報提供をしていかないと、前に進まないです。
２人とも、「動く」「動かない」としか言っていなくて、良くないです。

**Comment by chica-non** [comment]
テストした時点(3/12 12時半ごろ)では以下にコピーしたものが最新だと思ってテストしたのですが、26行目の ; が抜けてるのと } 括弧が多いみたいで、エラーになったんです。下記を保存しようとすると、「スクリプトに文法エラーがあります。 syntax error (#26)」となっていました。
例えば、https://raw.githubusercontent.com/Questetra/Addon-XML/c4025f687b273177ea4da5a179a3112212c36743/userCheck.xml をアドオンに保存しようとするとエラーが出ると思います。(この場合は「スクリプトに文法エラーがあります。 syntax error (#27)」と出ます。)
今後はリビジョンをチェックしてからテストします。新しいuserCheck.xmlがあるので、そちらでテストします。
---
<?xml version="1.0" encoding="UTF-8"?>
<service-task-definition>
	<label>CheckTheUserIsInTheGroup</label>
	<label locale="ja">ユーザの指定組織への所属を判定</label>
	<summary>If the specified user is the leader of the specified group,this task returns "L". If the he or she is one of the members of the group,it returns "M".If he or she doesn't belong to the group,it returns nothing.</summary>
	<summary locale="ja">指定したユーザが指定した組織のリーダであれば"L" を、メンバであれば"M" を、所属していなければ空を返します。</summary>
	<configs>
		<config name="userField" form-type="SELECT" select-data-type="QUSER" required="true">
			<label>I1.User Data</label>
			<label locale="ja">I1.ユーザデータ</label>
		</config>
		<config name="groupField" form-type="SELECT" select-data-type="QGROUP" required="true">
			<label>I2.Group Data</label>
			<label locale="ja">I2.組織データ</label>
		</config>
		<config name="result" form-type="SELECT" select-data-type="STRING_TEXTFIELD" required="true">
			<label>O1.Result</label>
			<label locale="ja">O1.結果出力先</label>
		</config>
	</configs>
	<script><![CDATA[
		  main();
		  function main(){
		  var groupIs = engine.findDataByNumber(configs.get("groupField"));
		  var userIs = engine.findDataByNumber(configs.get("userField"));
		  var result = ""
		    if (check(true,userIs,groupIs)) {
		    result = "L"
		    }else{
		        if (check(false,userIs,groupIs)) {
		        result = "M"
		        }
		    }
		    engine.setDataByNumber(configs.get("result"),result);
		  }
		  function check(LM,user,group){
		    var temp = "";
		    var list = quserDao.findByQgroupAndPosition(group,LM);
		    for (var i = 0;i<list.size();i++){
		      temp = list.get(i);
		      if(user.getId().equals(temp.getId())){
		        return true;
		      }
		    }
		  }
}
]]>
</script>
</service-task-definition>
---

**Comment by chica-non** [comment]
fd029607fe207a27b34ceba157cbcb076d2b87e8 をテスト。
 * 指定した組織のリーダの場合、サービスタスクは処理完了し、指定したデータ項目にLを返すこと
 * 指定した組織のスタッフの場合、サービスタスクは処理完了し、指定したデータ項目にMを返すこと
 * 指定した組織に所属しない場合、サービスタスクは処理完了し、空の文字列を返すこと
 * 組織の値が空だった場合、サービスタスクは処理失敗すること
  * スクリプトエラーが発生しました。 Wrapped java.lang.NullPointerException ('#20') 
 * ユーザの値が空だった場合、サービスタスクは処理失敗すること
  * スクリプトエラーが発生しました。 TypeError: Cannot call method "getId" of null ('#23')

気づいたこと
 * 処理失敗時のエラーメッセージが適切でない。例えば、「スクリプトエラーが発生しました。 組織を指定してください。 」とかの方がわかりやすい。
 * null チェックをした方がいいかもしれません。

ver. 11.6.0 rev. 34992 SaaS Edition

**Comment by R-Matsubayashi** [comment]
@chica-non 
6892d8b のテストをお願いします。

**Comment by chica-non** [comment]
@R-Matsubayashi 
6892d8b について修正を確認しました。
 * 組織が空の場合、サービスタスクは処理失敗し、自動処理ログに以下のように表示されること
   * スクリプトエラーが発生しました。 Organization Not Selected (#32)
 * ユーザが空の場合、サービスタスクは処理失敗し、自動処理ログに以下のように表示されること
   * スクリプトエラーが発生しました。 User Not Selected (#34)

気になること
 * サービスタスクの処理失敗した場合、「O1. 結果を保存する文字型データ項目」には空文字を返した方がいいと思います。

ver. 11.6.0 rev. 34992 SaaS Edition

**Comment by hatanaka-akihiro** [comment]
完了としてクローズします。
