### ISSUE TITLE
Line Push API を利用する Add-on を作成可能かどうか調べる

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#2]
https://developers.line.me/ja/docs/messaging-api/overview/

ボットは 現状の QBPMS の機能では、単独で実現不可能。

Push API の方は可能か。

Developer Trial プランで調べる。
https://at.line.me/jp/plan

**Comment by R-Matsubayashi** [comment]
やってみたのですが、どうしても以下のエラーが出ます。
{"message":"The property, '', in the request body is invalid (line: 1, column: 1)"}

body部は以下の通りです。
  .body({
    "to":"<id>",
    "messages":message
  },"application/json")
//messageはメッセージオブジェクト(JSON)

どうもbody部から空のpropertyが読み込まれてしまっているようですが、どう対処したものかわかりません。

**Comment by R-Matsubayashi** [comment]
var response = httpClient.begin()
  .bearer('<token>'
  )
  .body({"to":"<id>","messages":"<message>"},"application/json")
  .post('https://api.line.me/v2/bot/message/push');

以上が通信部です(エラーメッセージの出力部は割愛)。
APIの設定部で取得したtokenを使って通信、メッセージの送信先は固有のIDを使って指定します。
body部はJSONで、指定するプロパティは"to"(送信先IDの指定)と"messages"(送信するメッセージの指定。メッセージオブジェクト(これもJSON)を使う)の2つです。
しかし、上記のスクリプトで通信すると、上のcommentに書いたようなエラーが返ってきます。
”to"を"t"にしたり、IDを無効なものに変えたりしても同じエラーメッセージが出るので、空のpropertyが読み込まれているとすればこれより前と思われますが、そこからどうしたものかわからない、という状況です。
tokenの指定を間違っていた時はそこでエラーが出たので、token部分に問題はないと思われます。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

OAuth2 トークンは取得できていると思うので、curl で HTTP リクエストを送って、どういう結果になるか試してください。

なんとなくですが、リクエストボディに問題があるような気がするので、その部分を試行錯誤してください。
見た感じ、body() メソッドに JSON 文字列ではなく、JSON オブジェクトが渡っている気がしています。

**Comment by hatanaka-akihiro** [comment]
ちなみに JSON 文字列の作成は、JSON.stringify() を使うのが楽です。
こんな感じ。

```javascript
// Java の String のままだとエラーになるので、Javascript の String に変換している
var person = {
	"name" : String(engine.findDataByNumber(0)),
	"comment" : String(engine.findDataByNumber(1))
};

var jsontext = JSON.stringify(person);
```

**Comment by R-Matsubayashi** [comment]
空が読み込まれる問題は確かに文字列化で解決しましたが、今度はmessage部分でエラーが出るようになりました。こちらはJSON.stringify()を使ってもうまく行きません。
var messageT =         {
            "type":"text",
            "text":"Hello, world"
        }
 var message = JSON.stringify(messageT);
var temp = {
    "to":"U651184b55bcfb136e7db29cc09175ff8",
    "messages": message
  }
  var json = JSON.stringify(temp);
var response = httpClient.begin()
  .bearer('+pwFez38UY3+kHRu5n1pmsm2LaqSpoF7DkSsU+Z4lWhrDkeRumlIXH3xt+sbb12OlxtOw0pYbbOVBDnMT9Bm0nTOuZrNGzlfisGNjaGHDgRWlEPsXjR4F7CAOhXr1uGCfWEEi2Du4mPaCYLqxZDDagdB04t89/1O/w1cDnyilFU='
  )
  .body(json,"application/json")
  .post('https://api.line.me/v2/bot/message/push');

これがスクリプトで、返ってくるエラーは
{"message":"The property, 'messages', in the request body is invalid (line: 1, column: 54)"}
上記のスクリプトにおける変数jsonの中身が
{"to":"U651184b55bcfb136e7db29cc09175ff8","messages":"{\"type\":\"text\",\"text\":\"Hello, world\"}"}
です。
JSON.stringify()を使わなくても同じエラーが返ります。その際はjsonの中身が
{"to":"U651184b55bcfb136e7db29cc09175ff8","messages":{"type":"text","text":"test"}}
になっています。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

curl でうまくいったとのことですが、curl では、どのようなリクエストを送っていますか？
ドキュメントを詳しく見ておらず、「何だと問題ないのか」解らないので、どこに問題があるか答えられないです。

ちなみにですが．．．

```javascript
var message = {
  "type": "text",
  "text": "hogehoge"
};

var obj = {
  "to": "test",
  "messages": JSON.stringify(message)
};

var text = JSON.stringify(obj);
```

これで text の値は、以下のようになります。見やすく、整形しています。

```javascript
{
  "to" : "test",
  "messages" : "{\"type\":\"text\",\"text\":\"hogehoge\"}"
}
```

JSON.stringify() の使い方がおかしいと思います。

**Comment by R-Matsubayashi** [comment]
えっと、出来ました。messagesは配列で送らないといけないのに配列にしていなかったのが原因でした。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

チケットのタイトルから外れますが．．．

こちらの方が簡単かもしれない。こちらも調べてもらえますか。

https://notify-bot.line.me/doc/ja/

**Comment by R-Matsubayashi** [comment]
送信は出来ました。OAuthの設定さえすればすぐですし、少なくともPush APIよりはやりやすいですね。

**Comment by hatanaka-akihiro** [comment]
では、Line Notify の方を使うなら、どのような仕様になるか考えてください。

**Comment by R-Matsubayashi** [comment]
(1)OAuthの設定をしてもらう(入力内容はClient ID/Secretを含めて固定なので、テンプレートとして用意できるならそのほうが良いと思います)。トークン取得時にどのグループに投稿するかを設定する。
(2)投稿する。
の流れになりますね。OAuthさえ設定されていればあとはトークンを使って送信するだけです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

Add-on の設定項目（XML で言えば config 要素）を決めてもらいたかったですが、Add-on を作りながら考えてもらう形で良いでしょう。

> 入力内容はClient ID/Secretを含めて固定なので、テンプレートとして用意できるならそのほうが良いと思います

「テンプレート」とは、アプリ詳細-> OAuth 2.0 設定の設定画面にある入力支援のセレクトを指していると思います。Client ID / Secret は、オープン（誰にでも見える）にして良いものではないので、今の仕組みに乗せられない次第。現状の Add-on の仕組みではどうしようもないので、OAuth 2.0 の設定は別にしてもらう前提で進めてください。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

プルリクエストにはマージするコードに関することのみ記載し、それ以外はチケットに記載するようにしてください。

> LINE Notifyの仕様的に、Client ID / Secret はHelpあたりに書かざるを得ないわけですが、それは大丈夫なのでしょうか(サービスごとにClient ID / Secretが存在する仕様です。

仕様上、重要なことですね。Help に Client ID / Secret は書きません。それもオープンになっていることになるので、まずいです。

どうするかというと、アドオンを使用するユーザ自身に、Client ID / Secret を取得してもらう前提になります。もしユーザ自身が取得することができないなど、何らかの問題がある場合、Line Notify を使用した方法も見送ることになります。

Client ID / Secret の取得に関して、Line Notify の仕様がどのようになっているか、詳しく調べてください。

**Comment by hatanaka-akihiro** [comment]
完了としてクローズします。
