### ISSUE TITLE
userCheck.xml 「メンバ」という表現を「スタッフ」に変更

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#33]
QBPMS 内で「メンバ」という表現は使っていないので、「スタッフ」に変更する。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

修正お願いします。

Questetra BPM Suite 内と同じ言葉を使うように、注意してください。

なお今回は、他の人のテストは省略するので、しっかり自分でテストをした上でプルリクエストをしてください。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

> なお今回は、他の人のテストは省略するので、しっかり自分でテストをした上でプルリクエストをしてください。

テストをする前に、まずテストを設計してもらえますか。
「テストを設計する」といっても、さほど大きな機能ではないので、テストケースの洗い出しになります。

**Comment by R-Matsubayashi** [comment]
以下のことを確かめる
組織が入力されていない→エラー
ユーザが入力されていない→エラー
組織・ユーザが入力されていない→エラー

入力された組織が存在しない→エラー
入力されたユーザが存在しない→エラー
入力された組織・ユーザが存在しない→エラー

ユーザが組織のリーダーである→L
ユーザが組織のスタッフである→M
ユーザが組織に属していない→空白

これでよいのでしょうか？

**Comment by hatanaka-akihiro** [comment]
書き方としては、こんな感じで良いと思います。

- まず全体として、テストケースは２つに大別されます。見たところ、前者がないようです。
 - アプリでの設定について
 - プロセスにおいての Add-on の処理について
- 結果については、きちんと書いたほうが良いですね。「エラー」「L」「M」「空白」になるのは何？きちんと書けば、考察が足りていないところも見えてきます。

**Comment by R-Matsubayashi** [comment]
設定
設定するのは上から順に「組織型データ」「ユーザ型データ」「単一行文字型データ」である

実行時
組織だけが入力されていない→スクリプトエラー
ユーザだけが入力されていない→スクリプトエラー
組織・ユーザがともに入力されていない→スクリプトエラー

入力された組織が存在しない→スクリプトエラー
入力されたユーザが存在しない→スクリプトエラー
入力された組織・ユーザが存在しない→スクリプトエラー

ユーザが組織のリーダーである→O1に「L」を出力
ユーザが組織のスタッフである→O1に「M」を出力
ユーザが組織に属していない→O1を空白のままにする

初めからO1に文字がセットされていた場合でも機能するか？

これでどうでしょうか？

**Comment by hatanaka-akihiro** [comment]
設定項目については、「設定項目として存在しているか」だけでなく、「どういう設定項目か」についてのテストケースが必要です。例えば、「O1は単一行文字型データから１つデータ項目を選ぶ設定項目である」「O1 は必須で、指定しない場合、設定エラーになる」というようなことです。

「初めからO1に文字がセットされていた場合でも機能するか？」という観点に気づいたのは良いと思います。が、Add-on の処理の観点では O1 だけでなく全項目についてどうなるか着眼する必要があります。Add-on に対して、I1, I2, O1 の3項目入力があり、かつI1, I2, O2 の3項目出力があるというイメージです。入力のパターンを分類し、それぞれに対して Add-on がどう動作するか、出力がどうなるか記述する必要があります。

パターンは組み合わせも考慮すると、かなり多くなるなるはずです。例えば入力を「空」「空でない」の2値に分類したとしても、3項目あるので 2^3 = 8 パターンあります。分類が細かければ、もっと増えます。むろん、全パターンテストするかというと、テストしないです。コストがかかりすぎるので。ただテストを設計する段階においては、どういうパターンがあるのか意識するのが大事です。

**Comment by R-Matsubayashi** [comment]
設定

- I1:選択、ユーザ型データ、必須

- I2:選択、組織型データ、必須

- O1:選択、単一行文字型データ、必須

実行時
[I1:I2:O1]の順、「有効」は「ユーザ・組織が存在している」こと

- 有効:有効:空	→	正常動作
- 有効:有効:空でない	→	正常動作

- 無効:有効:空	→	スクリプトエラー"Selected user doesn't exist"
- 有効:無効:空	→	スクリプトエラー"Selected Organization doesn't exist"
- 無効:無効:空	→	スクリプトエラー"Selected Organization and User don't exist"

- 空:有効:空	→	スクリプトエラー"User Not Selected"
- 有効:空:空	→	スクリプトエラー"Organization Not Selected"
- 空:空:空	→	スクリプトエラー"Organization and User Not Selected"

- 空:無効:空	→	スクリプトエラー"User Not Selected"
- 無効:空:空	→	スクリプトエラー"Organization Not Selected"


正常動作

- ユーザが組織のリーダーである →O1に「L」を出力
- ユーザが組織のスタッフである →O1に「M」を出力
- ユーザが組織のメンバーでない →O1は空白のまま

こんな感じでどうでしょうか？

**Comment by hatanaka-akihiro** [comment]
- 設定に関するテスト項目。例えば「I1」の項目について何を確認すべきか、確認すべきことをリストアップしてみてください。例えば「必須」については、何を確認すべき？「ユーザ型データ」については、何を確認すべき？おそらく解っていると思いますが、きちんと書いてみましょう。

- 整理の仕方として、とても解りやすいです。以下、３点。
  - 正常動作にある、「O1 は空白のまま」は正しくないです。「O1 は空白になる」が正しい動きです。
  - さらに言えば、正常動作の場合、I1 と I2 はどうなる？
  - スクリプトエラーの場合、I1, I2, O1 はどうなる？

**Comment by R-Matsubayashi** [comment]
設定
I1:選択、ユーザ型データ、必須
I2:選択、組織型データ、必須
O1:選択、単一行文字型データ、必須

選択、**型データ → **型データの中から１つ選択する。**型データがない場合、「**型データが必要です」の表示になり、選択できない。
必須 → 選択されていない場合アプリがエラーになる。

実行時
[I1:I2:O1]
有効:有効:空	→	正常動作
有効:有効:空でない	→	正常動作

無効:有効:空	→	スクリプトエラー"Selected user doesn't exist"
有効:無効:空	→	スクリプトエラー"Selected Organization doesn't exist"
無効:無効:空	→	スクリプトエラー"Selected Organization and User don't exist"

空:有効:空	→	スクリプトエラー"User Not Selected"
有効:空:空	→	スクリプトエラー"Organization Not Selected"
空:空:空	→	スクリプトエラー"Organization and User Not Selected"

空:無効:空	→	スクリプトエラー"User Not Selected"
無効:空:空	→	スクリプトエラー"Organization Not Selected"

スクリプトエラーの場合、I1,I2,O1は変化しない。


正常動作
ユーザが組織のリーダーである →O1に「L」を出力
ユーザが組織のスタッフである →O1に「M」を出力
ユーザが組織のメンバーでない →O1に空白を出力

I1とI2は変化しない。

直しました。

**Comment by hatanaka-akihiro** [comment]
- 例えば I1 については、ユーザ型データ項目「しか」選択できない、他のデータ型の項目を選択できない、ことを確認することが重要です。このことから「他のデータ項目があるべき」「厳密には、全種類ある状態の方が望ましい」ということが見えてきます。
- O1 については、「単一行」という制約がついているので、複数行文字型データ型の項目は選択できないことを見た方が良いことになります。
- スクリプトエラーの場合、I1, I2, O1 は変化しないのですが、現在のテストケースで十分と言えるでしょうか？O1 については「空」のテストケースしかないので、実は「空にしている」可能性を否定できないです。

**Comment by R-Matsubayashi** [comment]
設定
I1:選択、ユーザ型データ、必須
I2:選択、組織型データ、必須
O1:選択、単一行文字型データ、必須

選択、**型データ → **型データの中から１つ選択する。**型データがない場合、「**型データが必要です」の表示になり、選択できない。
					→全ての型を用意して**型データのみが選択できることを確認する
必須 → 選択されていない場合アプリがエラーになる。

実行時
[I1:I2:O1]
有効:有効:空	→	正常動作
有効:有効:空でない	→	正常動作

無効:有効:空	→	スクリプトエラー"Selected user doesn't exist"
有効:無効:空	→	スクリプトエラー"Selected Organization doesn't exist"
無効:無効:空	→	スクリプトエラー"Selected Organization and User don't exist"

空:有効:空	→	スクリプトエラー"User Not Selected"
有効:空:空	→	スクリプトエラー"Organization Not Selected"
空:空:空	→	スクリプトエラー"Organization and User Not Selected"
空:空:空でない	→	スクリプトエラー"Organization and User Not Selected"
空:無効:空	→	スクリプトエラー"User Not Selected"
無効:空:空	→	スクリプトエラー"Organization Not Selected"

スクリプトエラーの場合、I1,I2,O1は変化しない。


正常動作
ユーザが組織のリーダーである →O1に「L」を出力
ユーザが組織のスタッフである →O1に「M」を出力
ユーザが組織のメンバーでない →O1に空白を出力

I1とI2は変化しない。

こういう感じでしょうか

**Comment by hatanaka-akihiro** [comment]
「空:空:空でない」のパターンを追加していますね。
間違いではないのですが、テストケースの選択の仕方として、上手でないです。

もともとスクリプトエラーになるケースが 8 ケースあったのですが、そのうちの半分について O1 を「空でない」ケースにする方が上手です。テストケースを増やさずに、スクリプトエラーになるパターンについて、O1 「空」「空でない」の両パターンを網羅できますので。

まとめたテストケースに従って、テストを行ってください。
テスト結果をチケットに記載するようにしてください。

**Comment by R-Matsubayashi** [comment]
f0b934d のテストを行いました。

UserCheck

設定
I1:選択、ユーザ型データ、必須
I2:選択、組織型データ、必須
O1:選択、単一行文字型データ、必須

選択、**型データ → **型データの中から１つ選択する。**型データがない場合、「**型データが必要です」の表示になり、選択できない。
					→全ての型を用意して**型データのみが選択できることを確認する
必須 → 選択されていない場合アプリがエラーになる。
→それぞれ指定された型のデータのみ選択できること、選択しない場合アプリがエラーになることを確認。

実行時
[I1:I2:O1]
有効:有効:空	→	正常動作　確認
有効:有効:空でない	→	正常動作 確認

無効:有効:空	→	スクリプトエラー"Selected user doesn't exist"　確認
有効:無効:空	→	スクリプトエラー"Selected Organization doesn't exist"　確認
無効:無効:空	→	スクリプトエラー"Selected Organization and User don't exist"　確認

空:有効:空	→	スクリプトエラー"User Not Selected"　確認
有効:空:空	→	スクリプトエラー"Organization Not Selected"　確認
空:空:空	→	スクリプトエラー"Organization and User Not Selected"　確認
空:空:空でない	→	スクリプトエラー"Organization and User Not Selected"　確認
空:無効:空	→	スクリプトエラー"User Not Selected"　確認
無効:空:空	→	スクリプトエラー"Organization Not Selected"　確認

スクリプトエラーの場合、I1,I2,O1は変化しない。　確認


正常動作
ユーザが組織のリーダーである →O1に「L」を出力　O1が空でない場合で確認
ユーザが組織のスタッフである →O1に「M」を出力　O1が空の場合で確認
ユーザが組織のメンバーでない →O1に空白を出力　O1が空の場合、空でない場合の両方で確認

I1とI2は変化しない。　確認

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

```
<help-page-url>https://support.questetra.com/addons/services/questetra-userorgposition/</help-page-url>
<help-page-url locale="ja">https://support.questetra.com/ja/addons/services/questetra-userorgposition/</help-page-url>
````

を入れてください。

またアドオンXML の仕様にはないのですが、最終更新日 (R-Matsubayashi の最終更新日) を以下のタグで入れてください。

```
<last-modified>2018-03-30</last-modified>
```

いずれも、ルート要素 <service-task-definition> 直下です。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

２つ追加。

- ファイル名を Questetra-userOrgPosition.xml にしてください。
- https://www.questetra.com/tour/m4/m415/check-the-user-is-in-the-organization/ にあるような設定ダイアログの画面キャプチャをって、このチケットに貼り付けてください。日本語の変更がなければ（ないと思いますが）、英語の画面キャプチャだけで良いです。

**Comment by R-Matsubayashi** [comment]
![ja](https://user-images.githubusercontent.com/36219261/39032473-a0cc5dc2-44a8-11e8-9663-af3b189e350f.png)
![en](https://user-images.githubusercontent.com/36219261/39032474-a21fff08-44a8-11e8-8432-2c96e53bc285.png)
日本語の方もサイトに今上がっている画像からは変わっているので、両方上げておきます。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

今の英語サイトの画面キャプチャを見ると、"Service" ではないようです。日本語サイトの方は「サービス」ですが。
英語サイトの方にあわせて、サービス / Service ではない名前でキャプチャした方が良いでしょう。

**Comment by R-Matsubayashi** [comment]
![en2](https://user-images.githubusercontent.com/36219261/39033097-62db73e2-44ab-11e8-96d6-1a77a96f1f1e.png)
![ja2](https://user-images.githubusercontent.com/36219261/39033098-630ab576-44ab-11e8-8fa7-5bf71ccc5c01.png)
やり直しました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

- 「ファイル名を変更してください」という話でしたが、名前変更前のファイルが残っているようです。
- こちらについても、細かいことは #8 と同じようにあるのですが、終わりにしようと思うので、省略します。

**Comment by hatanaka-akihiro** [comment]
完了としてクローズします。
