### ISSUE TITLE
Google Drive のファイルを削除する Add-on

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#45]
社内向け資料をベースに、Google Drive のファイルを削除する Add-on を追加する。

- チームドライブをサポートするように
- javascript で無名関数を使用しないようにリファクタリング
- 設定名など、ラベルの日英対応
- last-modified, help-page-url の追加

**Comment by tron-kmc** [comment]
>fileIds.split("\n").forEach(function(fileId) {
    deleteFile(token, fileId);
  });

この部分も無名関数はやめるべきでしょうか？

**Comment by hatanaka-akihiro** [comment]
> この部分も無名関数はやめるべきでしょうか？

いえ。ここは特に思っていないです。

**Comment by R-Matsubayashi** [comment]
>Google Driveのファイル削除 : フォルダは削除できるのですがファイルの削除ができません。原因を探っています。

の件ですが、「ファイルかフォルダか」が問題でないようです。QBPMSからアップロード/削除したものはファイルかフォルダかを問わず削除でき、そうでないものは出来ませんでした。だからPermissionの問題かと思いますが、それ以上はまだわかっていないです。

**Comment by hatanaka-akihiro** [comment]
> QBPMSからアップロード/削除したものはファイルかフォルダかを問わず削除でき、そうでないものは出来ませんでした。

OAuth2 トークンのスコープの話ですね。
Questetra BPM Suite で使用しているトークンのスコープにおいては、この動きは正しいです。
他にアップしたファイル（フォルダ）は削除できないはずです。

**Comment by R-Matsubayashi** [comment]
なるほど。なら仕様ということでそのままにしておいてよいのでしょうか。

**Comment by hatanaka-akihiro** [comment]
> なるほど。なら仕様ということでそのままにしておいてよいのでしょうか。

Add-on の側でどうにかできる話ではないです。
そのままにしておいて、良いです。

Add-on 自体、QBPMS によってアップロードされたファイルの削除を目的としたものです。

**Comment by R-Matsubayashi** [comment]
engine-typeを入れたものをcommitしました。

**Comment by R-Matsubayashi** [comment]
とりあえず、テストを設計しました。
https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit?usp=sharing

**Comment by hatanaka-akihiro** [comment]
「作成」と「削除」のシートがありますが、作成の方は前にテストをした「フォルダ作成アドオン」？
削除の方が「ファイル削除アドオン」？

その前提で、テストを見ています。

- 「EL 式で空白」とありますが、EL 式を指定できないのでは？「参照先のデータ項目の値が空」は、考慮しなければならない事象です。
- 「参照先のデータ項目の値が空」の場合、スクリプトエラーにして良いと考えます。テストの設計ではなく、アドオンの改良の話です。
- 実装としてはこのままで良いのですが、テストとして考慮しなければならない事象があります。現状、スクリプト内での HTTP リクエストの数には制限 (10) があります。つまり削除対象のファイル／フォルダ ID が多い場合、スクリプトエラーが発生するはずです。そのテストケースを加えてください。

**Comment by hatanaka-akihiro** [comment]
もう１つアドオンの改良をお願いします。

C1 の form-type を "QUSER" としてください。ユーザを選択できる設定項目になります。
ただし設定値 (configs の値) は、メールアドレスではなく、ユーザ ID になります。
それにあわせた、スクリプトの改良も必要です。

なお form-type="QUSER" は、11.8 から入る新機能です。
今のところ 11.8 は bpm.questetra.net にしかインストールされていません。

**Comment by R-Matsubayashi** [comment]
>「EL 式で空白」とありますが、EL 式を指定できないのでは？
>「参照先のデータ項目の値が空」の場合、スクリプトエラーにして良いと考えます。
>つまり削除対象のファイル／フォルダ ID が多い場合、スクリプトエラーが発生するはずです。そのテストケースを加えてください。
>C1 の form-type を "QUSER" としてください。

以上、テストとアドオンを直しました。

**Comment by hatanaka-akihiro** [comment]
テストをざっと見ましたが、特に問題はありません。

そのままテストに進んでください。

**Comment by R-Matsubayashi** [comment]
テストを行いました。
https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit?usp=sharing

No.4はbpm.questetra.netではできないと思うので保留しています。

**Comment by hatanaka-akihiro** [comment]
> テストを行いました。
> No.4はbpm.questetra.netではできないと思うので保留しています。

了解しました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

このチケットでのことじゃないかもしれませんが、以下２つのファイルは何だろ？

不要なファイルだと思うので、削除してもらえますか。

https://github.com/Questetra/Addon-XML/blob/master/google-drive%2C
https://github.com/Questetra/Addon-XML/blob/master/sh.exe.stackdump

**Comment by R-Matsubayashi** [comment]
消しました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

設定画面の画面ダンプをお願いします。日英両方とも。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

> 設定画面の画面ダンプをお願いします。日英両方とも。

ごめん。この件は取り消し。その前に。

- C1 の form-type を QUSER に変更してください。
- I1 の項目名を「削除するファイル・フォルダ ID が保存されている文字型データ項目」としてください。
- summary にて、「複数削除する機能があること」と「1行1ID」に言及してください。

その上で C1 がらみの再テストと画面ダンプもお願いします。

**Comment by R-Matsubayashi** [comment]
>I1 の項目名を「削除するファイル・フォルダ ID が保存されている文字型データ項目」としてください。
>summary にて、「複数削除する機能があること」と「1行1ID」に言及してください。

はしました( fe5da3c9fb0482f7d615fb92f0f47268f2b39e98 )。

>C1 の form-type を QUSER に変更してください。

は、テストしたバージョン( 01eef5a45abf6fa2156a829668caa421f802e18b )の段階ですでにQUSERになっています。

**Comment by R-Matsubayashi** [comment]
![c4553bbb6818554d918b5be9b59c720b](https://user-images.githubusercontent.com/36219261/47200017-47138800-d3af-11e8-9058-1c37eccb4ca9.png)

ここ、どうしたらいいでしょうか。システム的に誰かの名前を使わないといけないと思いますが。

**Comment by hatanaka-akihiro** [comment]
> テストしたバージョン( 01eef5a )の段階ですでにQUSERになっています。

なら、プルリクエスト忘れですかね。trunk のを見る限り、QUSER にはなっていないです。

ブランチのコードをちょっと見ましたが、属性の順番はそろえた方がきれいですね。
form-type と required の後先が、config 要素によって違っているようです。


設定画面のキャプチャ C1 の項目については、モザイクをかけるか、ユーザ名を「クエステトラ」とか無難な名前にしてください。

**Comment by R-Matsubayashi** [comment]
>ブランチのコードをちょっと見ましたが、属性の順番はそろえた方がきれいですね。
form-type と required の後先が、config 要素によって違っているようです。

順番を直してPRしました。

>設定画面のキャプチャ C1 の項目については、モザイクをかけるか、ユーザ名を「クエステトラ」とか無難な名前にしてください。

自分の名前を変えるというのは盲点でした。ありがとうございます。

**Comment by R-Matsubayashi** [comment]
![f4fc19b5b424d973508b1467d8ffea8b](https://user-images.githubusercontent.com/36219261/47201337-7678c380-d3b4-11e8-9a21-7f918fb2ae7e.png)
![fee42d75a6112ffc8d0a052f66111366](https://user-images.githubusercontent.com/36219261/47201339-77115a00-d3b4-11e8-930e-aa8a34ae08d0.png)

画面ダンプです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

マージしましたが、GoogleDrive-folderDelete.xml も `var token;` が try catch ブロックの中なのが気になります。

**Comment by R-Matsubayashi** [comment]
>マージしましたが、GoogleDrive-folderDelete.xml も var token; が try catch ブロックの中なのが気になります。

修正して(ついでに作成アドオンにtry-catchを追加して)テストをしました。
https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit?usp=sharing

**Comment by hatanaka-akihiro** [comment]
了解です。

たぶん、終わりになると思いますが、ちょっと待ってください。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

データ項目 I1。英語ラベルにて、"I1. " が抜けています。

英語の画面キャプチャも撮り直しで．．．

**Comment by R-Matsubayashi** [comment]
![f28fd2ff382a1db1de544fe09579e521](https://user-images.githubusercontent.com/36219261/47408757-938a0980-d79b-11e8-926c-3ba213be2e57.png)

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit?usp=sharing

飛ばしていた4番(該当ユーザがいない)のテストをしました。
作成と共有に関しても同じテストをしました。
#54 #46

**Comment by hatanaka-akihiro** [comment]
了解です。OK です。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

他と比較すると、これだけ Add-on のタイトルが動詞 (「削除する」) なので、改良してください。

Box 系の Add-on のタイトルも同じような感じ (例「BoxのWebhookを作成」)ですが、体言止めなのでギリギリ許容範囲か。

**Comment by R-Matsubayashi** [comment]
![6a85180f3660518656dd6272f7b936d0](https://user-images.githubusercontent.com/36219261/47891262-c9af4380-de95-11e8-81bd-d0b7f759a0ac.png)
画像です。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

ファイル削除のアドオンは、フォルダ作成と比較すると、ログ出力が少ないです。
特に正常時には、何のログも出ないので、ログ出力を増やしましょう。
API リクエストの応答に加えて、削除しようとしているファイルの ID もログ出力したいですね。

ログ出力のメッセージ。
> This User isn't connected with Google Drive.

This User has not connected with Google Drive.

あとユーザの名前かメールアドレスを、ログ出力に入れましょう。
(この点は、フォルダ作成のアドオンも同じか)

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

削除 API を呼び出すごとに、ファイル ID をログ出力するようにして欲しい。

11.9.0 に httpClient に１つメソッドを追加しました。

`httpClient.getRequestingLimit()`

で、スクリプト内で送信可能な HTTP リクエスト数の上限を取得できるようにしています。

これを使い、削除対象のファイル ID が多すぎて全て削除できない場合は、エラーではじくようにしてください。１つも削除せず、エラーではじく。

11.9.0 の環境は bpm.questetra.net しかないので、bpm.questetra.net で動作確認もテストも行ってください。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit#gid=359785136

テストしました(削除タブです)。

**Comment by hatanaka-akihiro** [comment]
> https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit#gid=359785136
> 
> テストしました(削除タブです)。

NO. 11 の項目は要らなくなったということが解るように。
ファイル (or フォルダ) を10個まで削除できるテスト項目を追加したほうが良いです。

**Comment by R-Matsubayashi** [comment]
>NO. 11 の項目は要らなくなったということが解るように。
ファイル (or フォルダ) を10個まで削除できるテスト項目を追加したほうが良いです。

直しました。新しいcommit分のテストもしました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

ちょくちょく変更すみません。
日本語で、"Google Drive" と表記しているところ、"Google ドライブ" に。
画面キャプチャもお願いします。

ついでに、変数宣言で var を使用しているところは、let または const に。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

タイトルについて再変更お願いします。すみません。

- Google ドライブ: ファイル削除
- Google Drive: Delete File

に。

**Comment by hatanaka-akihiro** [comment]
追加でさらに。

アイコンを

https://questetra.github.io/Icon-Maker/index.html

の「固定サービスタスクアイコン」にある「Google ドライブ」のアイコンにしてもらえますか。

**Comment by R-Matsubayashi** [comment]
![delete-en](https://user-images.githubusercontent.com/36219261/51457008-0bfc6880-1d93-11e9-9285-1be985374b0b.png)
![delete-ja](https://user-images.githubusercontent.com/36219261/51457009-0c94ff00-1d93-11e9-97c2-9e72d65a26fc.png)
キャプチャです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

```C1. Google ドライブに接続するユーザ```

コロンになっていない。。。

**Comment by R-Matsubayashi** [comment]
漏れてました……直しました。
![456b0b5185bf10562fab81052c635500](https://user-images.githubusercontent.com/36219261/51457739-e02eb200-1d95-11e9-8b19-16513cf2c0f2.png)

**Comment by hatanaka-akihiro** [comment]
完了として、クローズします。
