### ISSUE TITLE
 「Google Drive フォルダ生成」　「C1 ユーザの指定」の form-type を QUSER に

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#54]
「C1. Google Drive に接続するユーザ」の form-type を TEXTFIELD から QUSER に変更する。

設定内容が、メールアドレスの入力から、ユーザの指定に変わる。

**Comment by R-Matsubayashi** [comment]
テストはユーザー周りだけでいいですよね。

**Comment by hatanaka-akihiro** [comment]
> テストはユーザー周りだけでいいですよね。

正常系は１パターン。
異常系はユーザまわりだけで良いです。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1NbSUHzcioClTxnVNkgUk7P0JR4V9At_cpFGmj1CYWUI/edit?usp=sharing

テストできました(4はbpm.questetra.netでは出来ないのでしていません)

**Comment by hatanaka-akihiro** [comment]
> テストできました(4はbpm.questetra.netでは出来ないのでしていません)

自分で持っている環境があると思いますが、そちらでできないですか？

bpm.questetra.net と同じメールアドレスのユーザがいてダメだということはありません。

**Comment by R-Matsubayashi** [comment]
#45 で書いたとおり、4もすでにテスト済みです。

**Comment by hatanaka-akihiro** [comment]
了解です。

今後は、それぞれのチケットに記録が残るように、報告してください。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

設定画面が変わるはずなので、画面キャプチャをお願いします。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

英語の画面キャプチャもお願いします。

**Comment by R-Matsubayashi** [comment]
忘れていました。
![0d45ac9c4ee09e100919288f5e7ff10d](https://user-images.githubusercontent.com/36219261/47627698-d3266c00-db74-11e8-8709-884b50cc8a19.png)

**Comment by hatanaka-akihiro** [comment]
https://support.questetra.com/ja/addons/googledrive-foldercreate/

公開ページに反映されたので、クローズ。
