### ISSUE TITLE
Google Calendar 予定追加の改良

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#62]
https://support.questetra.com/ja/addons/googlecalendar-insertevent/

を改良する。

- 「OAuth2通信許可設定名」を「Google Calendar に接続するユーザ」に。Google Drive のアドオンと同じ形に。
- Calendar ID の指定を直接設定に。
- 予定タイトル / 場所情報 / 説明情報 / 情報元のタイトル / 情報元の URL の指定を直接設定に。EL 式可で。
- タイムゾーン / 通信ログに関する設定を無しに。ログは標準機能で出力。
- 設定のラベルの接頭辞は I1 / O2 / C3 形式に。

**Comment by R-Matsubayashi** [comment]
リンク先、説明と実際にダウンロードできるアドオンがかなり食い違っているんですが、説明に即したバージョンがあったりしませんか？

**Comment by R-Matsubayashi** [comment]
ありがとうございます。

**Comment by R-Matsubayashi** [comment]
タイムゾーンはシステムのタイムゾーンに合わせる形にしていますが、それで大丈夫ですか？

**Comment by hatanaka-akihiro** [comment]
日時型データは、システムのタイムゾーンを前提にした値ですので、それを使う必要があると思います。

質問のポイントは違いますか？

**Comment by R-Matsubayashi** [comment]
『APIにタイムゾーンの情報を送らないとエラーになるが、「タイムゾーンの設定はなくす」という指示があったので、システムのタイムゾーンから情報を生成して送ることにしている』ということが言いたかったです。大丈夫そうですね。

**Comment by R-Matsubayashi** [comment]
テスト設計をしました。
https://docs.google.com/spreadsheets/d/1k7QVm04PQ5qD4_JlAUDzeLpp2BvcsHeGVJghKXmMTBY/edit?usp=sharing

e9e7a2c2cf9c6ea0c4b18cf24535dc5a55ad9fd6 でやります。

**Comment by hatanaka-akihiro** [comment]
branch のコードを見ましたが、summary にある「ログを出力します」は不要ですね。

他のことを書いた方が良いです。

**Comment by hatanaka-akihiro** [comment]
> テスト設計をしました。
> https://docs.google.com/spreadsheets/d/1k7QVm04PQ5qD4_JlAUDzeLpp2BvcsHeGVJghKXmMTBY/edit?usp=sharing

気になったのは、EL 式可・TEXTFIELD の設定項目で、EL 式の結果が複数行になった場合、どう動くか。

**Comment by hatanaka-akihiro** [comment]
これのタイトルは

Google カレンダー: 予定追加
Google Calendar: Insert Event

に。

**Comment by R-Matsubayashi** [comment]
>気になったのは、EL 式可・TEXTFIELD の設定項目で、EL 式の結果が複数行になった場合、どう動くか。

直してみました。

**Comment by R-Matsubayashi** [comment]
テスト、 https://docs.google.com/spreadsheets/d/1k7QVm04PQ5qD4_JlAUDzeLpp2BvcsHeGVJghKXmMTBY/edit?usp=sharing これでやっていいでしょうか？

**Comment by hatanaka-akihiro** [comment]
> テスト、 https://docs.google.com/spreadsheets/d/1k7QVm04PQ5qD4_JlAUDzeLpp2BvcsHeGVJghKXmMTBY/edit?usp=sharing これでやっていいでしょうか？

そうですね。

あと気になったところとしては、「予定がセットされる」として、それぞれの設定は Google Calendar の予定のどこに反映されるのか、それがよく解らないところでしょうか。

**Comment by R-Matsubayashi** [comment]
![c643ede2153bed10b71105d79e72c70b](https://user-images.githubusercontent.com/36219261/49357683-5ce8cc80-f713-11e8-820e-2845813fe3f1.png)
こういう感じです(こういう話で合ってますか？)。
「確認メールを表示」がC7のURLへのリンクになっています。
C6は今は出ないそうです(バグという話もあり)

**Comment by hatanaka-akihiro** [comment]
あっていますよ。ビジュアルで説明してほしかったわけではないですが、解りやすいですね。

> 「確認メールを表示」がC7のURLへのリンクになっています。
> C6は今は出ないそうです(バグという話もあり)

「確認メールを表示」と出るのはダサいですね。
本来は「情報元のタイトル」がここに出るはずだったのだろうか。

「バグという話もあり」というのは、どこかから見つけた情報ですか？

「情報元のタイトル」「情報元の URL」を、設定項目として残すか削除するか、考えています。

**Comment by R-Matsubayashi** [comment]
>「バグという話もあり」というのは、どこかから見つけた情報ですか？

https://stackoverflow.com/questions/48135225/source-title-and-url-not-displayed-in-google-calendar-when-using-calendar-api
https://issuetracker.google.com/issues/73334552

このあたりでバグとして話されていたのでそう書きました。

**Comment by hatanaka-akihiro** [comment]
なるほど。

いったん「情報元のタイトル」「情報元の URL」の設定項目は無しで。

設定項目自体を非表示にするだけで、それを登録するコードは残しておいてください。

Google Calendar の側が復旧したら、元に戻したいと思うので。

**Comment by hatanaka-akihiro** [comment]
「C3: 予定タイトル」以降、I1, I2 と番号を振り直してもらえますか。

テストは番号の降り直しに耐えられるように、ラベルを記載するようにしてください。

あと Calendar ID の空を許すようにし（required をやめる)、空の場合はプライマリのカレンダーに登録するようにしましょう。確かプライマリのカレンダーの id は "primary" だったかな。調べてください。

**Comment by R-Matsubayashi** [comment]
これでテストしてよいでしょうか？

**Comment by hatanaka-akihiro** [comment]
ざっと見たところ、問題なさそうです。
テスト進めてください。

「それぞれの設定は Google Calendar の予定のどこに反映されるのか」の画面キャプチャは、重要な情報なので、Spreadsheet の中にもはりつけておいた方が良いです。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1k7QVm04PQ5qD4_JlAUDzeLpp2BvcsHeGVJghKXmMTBY/edit?usp=sharing

テスト完了しました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

いつも通り、画面キャプチャもお願いします。

**Comment by tron-kmc** [comment]
![598adc00c855955bd2b024c58b8e46a1](https://user-images.githubusercontent.com/19284538/49629002-a9414e80-fa2a-11e8-8978-eb8dd5a41e26.png)
![cae2abe4e2fc43fa3ef8249e88c6d4db](https://user-images.githubusercontent.com/19284538/49629003-a9d9e500-fa2a-11e8-9a31-5bcfb7743945.png)
キャプチャです。

**Comment by R-Matsubayashi** [comment]
またアカウントを間違えた……

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

以下の修正をお願いします。
- スクリプトの先頭にある、以下のコメントを削除。
```
// Insert Event to Google Calendar via Calendar API v3 (ver. 20161025)
// (c) 2016, Questetra, Inc. (the MIT License)
```
- 以下のタグを、last-modified の次に入れる。将来対応予定のタグです。
`<license>(C) Questetra, Inc. (MIT License)</license>`

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

もう１つ。「Google Calendar」と表記されているところ、「Google カレンダー」に変更してください。もちろん日本語のみです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

このアイコンに変更してください。

ラベルの変更に伴い、設定ダイアログの再キャプチャも忘れずに。

```
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEt0lEQVRYR8VXX2xTVRj/ndv2tmv3
p1cGDyqM8SBRx9jcNBEMW7apSMKYMWoiD9sSEhITQ33AB23DyOaDJmoxGqPRbBgwEhMdUSRKS4ri
XMA/I4jJhkZQIEhgbdm69ra395hz72572t5u3UbwvDS99/vO+Z3v+/2+77sE//MiCzm/vT/cRYjQ
AtAGAG4A7JetMQARgIwBJBTwVh4udd95AbT2hd1Wm7CLqtRDiHbovItSRIhA/EpK3RfqkyJzOcwJ
oO3VcA9RyVulHpx/EAMC0N6gTxouBqIogPb+sJ8Qsmve65ZkQPwBb9WLZqamANoHwkMEpLukvUs0
oiBDQW9Vb755AQD+5utrrGirs8FmmZcqpjAmp1UcPJlAPKm/ppTuC/okD2+cszPLuUDJoGHwTm85
1t5p0f5ejaoYnVCwuUGEw2Z+7ZkkcPy3JDautUFyEagUGD6dxHvH4hkHSumTPCcyABjbLRbyF0+4
D3dWoKZa0Jwvh1WEzqXQ9aAdLrs5gJgMfP2rjLY6EcvK9a2PjiXx5hEeACLpNK011JEB0NEf7gMh
e4ytm9dY0V4ngpaYYzMzgQBTCYpDIwlcn+J2onRvwCf1MZ8sgIEwKyRVxkb+7nLcf7ce/qWstAp8
fkrGB8EElwZEgj63lAGgVzjyBX/Q69tdaFxtXcrZmm8qDRwakbH/uyyAWUJqXNAiYKb53VudeKy+
CNsWAIsp4N1v4/jmzKwUZn0NRWgAOvrDIRDSwu/b0+LAMw/bYeOy8PcNFYOhBG5MqRo/Hq0X4RQB
Rr7xKwrGLirY1mTHsoqsuCIxijeOzGD0vJILm9ITAZ/UqkdgIHyBgNTwFtuaRexoK8tIjpHp4EkZ
Tz1kR3UlwU9/KojJVJPc8GkZVU4BlybT6Gyyo5oDwNTzyqcxXJ5U8+M2FvC6G/UIDEQKyL7pXhs8
T5Shoky/DdM0y6do1Zl7aVLFqT9S6Gy2g7Gdke3Ln5NgfjyA81fTeP6jadOkBbxuUhRA3UoLXu5y
YXllbhWUFeBaVMWxs0m03idizQq9TjBwZgBGJhTs+Sw2NwCzFNx1h4DnNjrgduUCiMsUCYXi93/S
WFUtYGW1ThIWgdGJFNatsqLSmfUZv5LGx3kKmFXBmaBPaihKwgdqrXip05mpaPlX+DdK8dUvMrY/
4tB4UiwCjJi7D5hEIIeEJq23Y50NL2x2aixni/WCHycUbG0SYRWAUgFcvK5ix/tTBSnIkaFZIere
5MCzG7IyZCRkveDaTRW1KywYGdf7Qu08HGAl+LXDM5pE+WU0paKl2LOlDFsaxWytZu0UwHSC4mac
YnmFoCnCWAwgAye5BNi556xGvH10BsfPpbjzaTTglbTxrmgz2vu0CxvuuTWl+JMfEjjwvZwFYNaM
tOHTigtGQ+JngQVU3gLTwpmARhUFqwvaMfPkB5KdHQ48Xi/CsshpyEAyHacYPBFH4KyegqIDieFw
a4fRvIBwoTfe3MahlO4PeqWe/BzdnrHc5OZzRoBLRxchGOInpYURkkYpRc+iPkyMgzR1WOABgad0
IDQKCr+Shn9Jn2b5t2UVEwAbIhoo4CaErDcaCwFYT2cfqaG5blwyBxYW6sVb/wdgbxw/u9E3bAAA
AABJRU5ErkJggg==
```

**Comment by R-Matsubayashi** [comment]
![a385342b31142798e8c80c9b726de767](https://user-images.githubusercontent.com/36219261/49848051-9063df00-fe16-11e8-8c8f-265a0e70406a.png)
新しいキャプチャです。

**Comment by R-Matsubayashi** [comment]
![d9bd46e0560d931b14d82500eaee2513](https://user-images.githubusercontent.com/36219261/51456966-e8d1b900-1d92-11e9-8499-0c509c5bcc90.png)
![2ad02cd49539d5e8e5c2fca0b361f5e2](https://user-images.githubusercontent.com/36219261/51456968-e96a4f80-1d92-11e9-8c09-ccf67b9a574d.png)
キャプチャです。

**Comment by hatanaka-akihiro** [comment]
完了として、クローズします。
