### ISSUE TITLE
Google ドライブ フォルダ作成 細かい改修

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#66]

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

フォルダ作成のアドオンについても、日本語で "Google Drive" と表記しているところ、"Google ドライブ" に変更お願いします。

画面キャプチャもお願いします。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

タイトルについて再変更お願いします。すみません。

Google ドライブ: フォルダ作成
Google Drive: Create Folder

に。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

追加でさらに。

アイコンを

https://questetra.github.io/Icon-Maker/index.html

の「固定サービスタスクアイコン」にある「Google ドライブ」のアイコンにしてもらえますか。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

ちょっと細かくない改修。

親フォルダ ID の必須をやめ、空の場合は「マイドライブのルート」に作成するようにしましょう。

- サービスタスク (Google ドライブ) は、空の場合、マイドライブのルートにアップする
- 先日作ってもらった Google カレンダのやつも、カレンダ ID を指定しなければ、プライマリカレンダに予定を追加する

この辺から考えると、空を許容し、空の場合は「マイドライブのルート」にするのが適当と思ったので。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

すみません。こちらについても

`<license>(C) Questetra, Inc. (MIT License)</license>`

の追加をお願いします。フォルダ作成／ファイル削除／ファイル共有の３種類ともお願いします。

**Comment by R-Matsubayashi** [comment]
https://drive.google.com/drive/folders/1k7aBT-Btdk2yuZ5T0tFHJGe4eZYLVUTV?usp=sharing
ここに上げました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

「共有」以外は、それぞれチケットが残っているので、それぞれのチケットに貼り付けてもらえますか。

「共有」はこのチケットで構わないです。

**Comment by R-Matsubayashi** [comment]
![create-ja](https://user-images.githubusercontent.com/36219261/51456736-25e97b80-1d92-11e9-9a30-12812b9d3bc3.png)
![create-en](https://user-images.githubusercontent.com/36219261/51456739-271aa880-1d92-11e9-9f59-1e019865f3e3.png)
![permission-ja](https://user-images.githubusercontent.com/36219261/51456744-2da92000-1d92-11e9-8643-8dbbdb7cf57e.png)
![permission-en](https://user-images.githubusercontent.com/36219261/51456748-2eda4d00-1d92-11e9-9f88-3deded4fac4a.png)
では、「作成」と「共有」です。

**Comment by hatanaka-akihiro** [comment]
完了として、クローズします。
