### ISSUE TITLE
Slack メッセージを投稿する

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#76]
Incoming-Webhook を使って、メッセージを投稿するボットを作成する。

Bots とどちらにするか悩んでいる。

**Comment by R-Matsubayashi** [comment]
単にメッセージをPOSTするだけのアドオンでいいですか？それともattachmentsも使えるほうにしたほうがよいですか？

**Comment by hatanaka-akihiro** [comment]
> 単にメッセージをPOSTするだけのアドオンでいいですか？それともattachmentsも使えるほうにしたほうがよいですか？

Incoming-webhook で、ファイル添付もできるのですか？

できるなら、一度、ファイル添付も可能なように作ってもらえますか。

どうなるのか、見てみたいです。

**Comment by R-Matsubayashi** [comment]
ファイルは無理そうですね(attachmentsはテキストの装飾に使うものです)。

**Comment by hatanaka-akihiro** [comment]
attachments のドキュメントを見ました。

よく使いそうなものがあれば、対応したいところです。

**Comment by R-Matsubayashi** [comment]
とりあえずfallback,color,title,title_link,textの5つに対応させてみます。

**Comment by R-Matsubayashi** [comment]
現状attachmentsのうちfallback,color,title,title_link,textのみ使えて、author関連、画像、fields、footer関連は使えず、またボタンなども使えない、という状況ですが、これでテスト設計してよいでしょうか？

**Comment by hatanaka-akihiro** [comment]
構わないですよ。

ところで fallback を Questetra でどう使ったら良いか、説明できます？

私は、どう使ったら良いか解らないので。

**Comment by R-Matsubayashi** [comment]
「attachmentsが表示できない環境で見る時用に、とりあえず設定しておくべきもの」という認識でした。
実際、ドキュメントにも"Required"と書いてあるので。

**Comment by hatanaka-akihiro** [comment]
callback する機能かと勘違いしていたわ。了解です。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/11U0ig-b1hKT3Rp34AaJWP44DtOcE3ABCHphnSN_4gVA/edit?usp=sharing
こんなところでしょうか。

**Comment by hatanaka-akihiro** [comment]
カレンダーのときと同じように、どの設定がメッセージのどこに反映するか、画面キャプチャを入れてもらえますか

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/11U0ig-b1hKT3Rp34AaJWP44DtOcE3ABCHphnSN_4gVA/edit?usp=sharing
これでテストしていいですか？

**Comment by hatanaka-akihiro** [comment]
Attachment の色 は EL 式不可でも構わないと思います。
利用シーンが思いつかないし、EL 式不可の方が少しでもテストを簡略化できるので。

Attachment のタイトルが空だと、リンクがあっても意味がないようですが、そのチェックはスクリプトのレベルでしてしまっては？

テキストもフォールバックも未設定の場合、通知の表示はどうなりますか？
テキストも Attachemnt も未入力の場合、投稿はどうなるんだろ。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

Incoming-Webhook 版と Bots 版の両方作成しようと思います。よろしくお願いします。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/11U0ig-b1hKT3Rp34AaJWP44DtOcE3ABCHphnSN_4gVA/edit?usp=sharing

テスト直したのと、Bots版を作りました。
Bots版も機能はincoming webhook版と同じです。

**Comment by hatanaka-akihiro** [comment]
Bots 版だったら、ファイル添付できないですか？ (API を知らずに、質問しています)

- テキストも Attachment も空で、フォールバックだけ
- 全部空

は、エラーではじいて問題ないです。
「そんな使い方あるのかな？」と思うケースは、エラーで構わないです。
要望があってから、変更することもできますし。

**Comment by R-Matsubayashi** [comment]
ファイルのアップロードはできますが、テキストに添付という形にはできないですね(POSTする先が違うので)。
ファイルにコメントをつけるという形でファイルとテキストを同時に送ることはできますが、その場合ファイルが必須になりますし、attachmentも使えませんので、別のアドオンを作るべきかと。

**Comment by hatanaka-akihiro** [comment]
なるほど。ではファイルは諦めましょう。

もしかして Incoming webhook 版と Bots 版、リクエスト先の URL が異なるだけで、他は全く同じですか？

**Comment by R-Matsubayashi** [comment]
ちょっと違います。Botsのほうは投稿するチャンネルの指定が必要なので。

**Comment by hatanaka-akihiro** [comment]
了解です。

URL が異なるだけなら、１つのアドオンにまとめようかと考えましたが、必要な設定に違いがあるのですね。

別々のアドオンのままで進めてください。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

ファイル名を変えました。注意してください。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

help-page-url を以下の通りにしてください。

https://support.questetra.com/ja/addons/slack-chat-post-webhook/
https://support.questetra.com/addons/slack-chat-post-webhook/

https://support.questetra.com/ja/addons/slack-chat-post-bots/
https://support.questetra.com/addons/slack-chat-post-bots/


「Attachmentのタイトルリンク」の英語ラベルは "Attachment Title Link" の方が良いです。
"Title Link" だと、"Attachment" に関するものであることが解らないので。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/11U0ig-b1hKT3Rp34AaJWP44DtOcE3ABCHphnSN_4gVA/edit?usp=sharing

テストしました。なぜかBots版はBotのJoinしていないチャンネルにも投稿できました(Slack側の設定の問題でしょうか)。

**Comment by hatanaka-akihiro** [comment]
> なぜかBots版はBotのJoinしていないチャンネルにも投稿できました

確かに変な感じがしますね。プライベートチャンネルでも投稿できるのでしょうか。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

```Slack: Post Chat ((Bots)```

Bots 版の英語ラベル。誤字があるようです。

**Comment by R-Matsubayashi** [comment]
プライベートチャンネルはさすがに無理でした。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

誤字を見つけました。" が要らない。
```C7:"Attachment Title Link```

"C7:" の後ろにスペースを１つ入れるようにしてください。日英両方とも。
Google 系のアドオンも、同じように修正してください。

また "I1." と、ピリオドが使われているパターンもあるので、それも ":" に統一してください。

**Comment by R-Matsubayashi** [comment]
キャプチャはアドオン版のものでよいですか？

**Comment by hatanaka-akihiro** [comment]
> キャプチャはアドオン版のものでよいですか？

「公式アイテム版でなくて…」という質問の意図ですかね。

どちらでも構わない、アドオン版でも構わないです。

**Comment by R-Matsubayashi** [comment]
![9db5824258ec9d2b06d3c5234386b943](https://user-images.githubusercontent.com/36219261/51461867-90a2b300-1da2-11e9-8019-bc894718f66e.png)
![f83d2a079f726840827684450c908587](https://user-images.githubusercontent.com/36219261/51461868-913b4980-1da2-11e9-920e-fd7590f2acfa.png)
![43d1903c23d7418fc71efc5677fcfb05](https://user-images.githubusercontent.com/36219261/51461870-926c7680-1da2-11e9-90ec-6ac050d4bdc6.png)
![d363118db8ac05d13db045bd25bb5c1a](https://user-images.githubusercontent.com/36219261/51461871-93050d00-1da2-11e9-99f9-5b936a5851a2.png)
キャプチャです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

引き続き "Slack App" について、調査をお願いします。
"Slack App" として独自の App を作った場合、Bots とどう違うのか調べてもらえますか。

**Comment by R-Matsubayashi** [comment]
Slack AppはIncoming WebhookとかBotsなどの自動処理する機能をひとまとめにしたもの、ということらしいです。
Slack側のアクションに反応して動かすための機能がほとんどで、一方的にSlackに送信するだけなら特にIncoming WebhookやBotsと違いはなさそうですね。

**Comment by hatanaka-akihiro** [comment]
Bot ユーザとしてのメッセージ投稿ではなく、一般ユーザとしてメッセージが投稿できると思います。

それも Bots や Incoming Webhook で実現できますか？

**Comment by R-Matsubayashi** [comment]
それは確かにできなさそうです。

**Comment by hatanaka-akihiro** [comment]
「一般ユーザとしてのメッセージ投稿」の利用シーンが、私にはちょっと思いつかないですね。

メッセージ投稿に限らず、QBPMS との組み合わせで何か面白いことができないか、調べてもらえますか。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/11U0ig-b1hKT3Rp34AaJWP44DtOcE3ABCHphnSN_4gVA/edit?usp=sharing

テストし直しています。

**Comment by R-Matsubayashi** [comment]
Botについて。てっきり「Customize Name」がSlack上で表示される名前なのかと思ったのですが、こちらの環境ではどうしても「Full Name」のほうが表示名になります。他の環境の状況も知りたいのですが、そちらで使っている環境ではどうなるか教えていただけますか。

**Comment by R-Matsubayashi** [comment]
今気づいたのですが、チャンネルの指定はIDだけでなく、チャンネル名でもいけるようです。

**Comment by hatanaka-akihiro** [comment]
私はずっとチャンネル名を指定して使っていたようです。

チャンネル名で良いです。設定名も変更してください。

**Comment by R-Matsubayashi** [comment]
![8038e26268b568ec8287e6230a49ffd7](https://user-images.githubusercontent.com/36219261/52845189-d193aa80-3149-11e9-90f2-b65449988cb9.png)
![1acdfa1df015d6a574219295c748982e](https://user-images.githubusercontent.com/36219261/52845195-d22c4100-3149-11e9-9e91-1416fadb6cda.png)
新しいキャプチャ(bot版)です。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

チャンネル名に # が必要なのは、Slack 側の仕様としては、それが正しい？

# 抜きでも動作すると思っていたので。

**Comment by R-Matsubayashi** [comment]
ドキュメントに#付きで書いてあったのでそれが正しいと思って書いていましたが、確かになくても動きますね。

**Comment by hatanaka-akihiro** [comment]
> ドキュメントに#付きで書いてあったのでそれが正しいと思って書いていましたが、確かになくても動きますね。

もう１つ気になったのは、private チャンネル。
チャンネルの一覧で、private チャンネルはシャープが表示されていない。
private チャンネル宛も、シャープ付きで動作するんですかね。

**Comment by R-Matsubayashi** [comment]
>private チャンネル宛も、シャープ付きで動作するんですかね。

動きました。

**Comment by R-Matsubayashi** [comment]
とはいえ、ないほうがわかりやすいので、「#付き」は外そうかなと思っています。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

last-modified の変更が漏れていましたが、こちらで対応しました。

再び設定画面のキャプチャをお願いします。

組み込み済みのものの、設定画面をキャプチャしてください。(「定義ファイル」の項目がありません)
bpm.questetra.net には反映済みです。

**Comment by R-Matsubayashi** [comment]
![c3f942fb653ec930e718cccff6344e76](https://user-images.githubusercontent.com/36219261/53618042-1846d180-3c2d-11e9-8192-6d4174001959.png)
![22d0bfd1f46af98c2661b86dc2acce33](https://user-images.githubusercontent.com/36219261/53618045-18df6800-3c2d-11e9-8f11-4e2b035068ee.png)
日本語のキャプチャです。

**Comment by R-Matsubayashi** [comment]
![fb079dfdd84241a6ed7289024f6e2dce](https://user-images.githubusercontent.com/36219261/53618066-33194600-3c2d-11e9-99ba-62a190b82fff.png)
![e687cfe950fba87e37a27515fcc67c27](https://user-images.githubusercontent.com/36219261/53618067-34e30980-3c2d-11e9-8e6b-f3faa917cd6c.png)
英語のキャプチャです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

Box 版だけのつもりでしたが、Incoming-Webhook 版もありがとう。
両方とも画面キャプチャを更新しました。

https://support.questetra.com/ja/addons/slack-chat-post-bots/
https://support.questetra.com/ja/addons/slack-chat-post-webhook/

本チケットもクローズします。
