### ISSUE TITLE
Line Notify を使用して Line にメッセージを送信する Add-on

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#8]
Line Notify を使用して、Line にメッセージを送信する。

仕様は #2 で決まった内容に従う。

**Comment by R-Matsubayashi** [comment]
やはり、Client Id/Secretは管理者のみが取得できる仕様です。ユーザーが知るには管理者が教える以外ありません(そもそもClient Id/Secretを使って通信して初めて連携可能なので、Client Id/Secretを知らなければLINE Notify上でQBPMSの存在を認知さえできない)。となると、現状のQBPMSでClient Id/Secretを表に出さずにLINE Notifyを使う方法はないと思われます。

**Comment by R-Matsubayashi** [comment]
ユーザーにサービス登録させるよりも、サービス登録無しでアクセストークンを発行する機能があるので、そちらを使ったほうが簡単ですね。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

コードを見ました。

アクセストークンは、入力項目ではなく設定項目ですので、"C1" ですね。

スクリプトについてですが、「処理がうまくいかない場合」の考慮が足りないです。
response をみる必要があるでしょう。

またサポート／デバッグのことも考えて、ログ出力も重要です。

**Comment by R-Matsubayashi** [comment]
使用方法です。
1.LINEのアカウントでLINE Notify(https://notify-bot.line.me/)にログインする。
2.「マイページ」の下部にある「アクセストークンの発行(開発者向け)」でパーソナルアクセストークンを発行する。
3.設定画面の「C1.アクセストークン」に発行したアクセストークンを入力する。
4.指定した文字型項目に任意の文字列を入力して実行。

**Comment by hatanaka-akihiro** [comment]
１つ気になっているのですが、誰宛にメッセージが届くのでしょうか？
本人だけですか？

IFTTT では、Line Notify を含むグループを作成して、そのグループ宛にメッセージが届くようにしました。
どのグループ宛にメッセージを送るか、IFTTT で設定した記憶があります。

**Comment by R-Matsubayashi** [comment]
アクセストークンを発行したユーザーの参加しているグループならばどのグループでも投稿可能です。
そこはIFTTTと同じですね。

**Comment by hatanaka-akihiro** [comment]
> アクセストークンを発行したユーザーの参加しているグループならばどのグループでも投稿可能です。

アドオンのプログラムを見る限り、どのグループに投稿するか制御していない感じですが、そのあたりはどうなっているのでしょうか？

**Comment by R-Matsubayashi** [comment]
投稿先はアクセストークン発行時に選択する仕様です。なので、投稿先を変える場合はトークンは複数必要ですね。

**Comment by hatanaka-akihiro** [comment]
なるほど。
パーソナルアクセストークンではなく、OAuth のトークンを取得するときも同じですかね？
(IFTTT でどうだったか、細かいことを覚えていないのです）

ユーザが、Line Notify から OAuth のトークンを取得することを認めるタイミングで、どこ宛に投稿するか、選択でしたかね？

**Comment by R-Matsubayashi** [comment]
そうです。

**Comment by hatanaka-akihiro** [comment]
> アクセストークンを発行したユーザーの参加しているグループならばどのグループでも投稿可能です。

Line Notify を含んでいないグループでも OK でしたっけ？

またグループが１つもない場合、どうなるのでしょうか。そもそもトークンを取得できない？

**Comment by R-Matsubayashi** [comment]
LINE Notifyを含んでいないグループにメッセージを送った場合、LINE Notifyを参加させるよう警告が来ます(トークンを発行したユーザー宛に)。
グループが１つもない場合は、グループが１つもないLINEアカウントを持っていないのではっきりとは言えませんが、「1対1で通知を受け取る」という項目もあるので、それだけが使用可能になるかと。

**Comment by hatanaka-akihiro** [comment]
つまるところ、「自分宛」or「自分を含むグループ宛」にメッセージを送られるわけですね。

宛先の選択がどのようになっているか、使用方法の説明にきちんと書いた方が良いです。

またアドオンの側にも、あて先に関する言及があった方が良いです。
私が質問したということは、何も知らない人も同じように思うはず。

**Comment by R-Matsubayashi** [comment]
アドオンの側で言及というのは、
・コメントアウトで書いておく
・設定項目の項目名にその旨を書く
といった感じでしょうか？

**Comment by hatanaka-akihiro** [comment]
設定項目の項目名や、アドオン自体の説明 (summary) ですかね。

アドオンを使用してアプリを作成するユーザに対して、どこ宛にメッセージを送るか、言及したほうが良いと思います。

**Comment by R-Matsubayashi** [comment]
上のPull Requestは間違いです。

**Comment by R-Matsubayashi** [comment]
@chica-non 
9d9afcd のテストをお願いします。
使い方
https://notify-bot.line.me/ja/ にアクセスしてLINEアカウントでログインし、マイページの下にある「アクセストークンの発行(開発者向け)」からトークンを発行します。送信先は「1:1で～」でよいでしょう。
設定項目C1にそのトークンを入力し、I1に文字型項目(単一行・複数行は問いません)を指定します。
I1に指定した項目にテキストを入力して実行すると、LINE Notifyからそのテキストが送信されます。
文字は0文字、あるいは1001文字以上の場合エラーを返すので、その部分のテストもお願いします。

**Comment by chica-non** [comment]
@R-Matsubayashi 
9d9afcd のテストしました。
1. https://notify-bot.line.me/ja/ にアクセスしてLINEアカウントでログインし、マイページの下にある「アクセストークンの発行(開発者向け)」から、トークンを発行
   * トークン名「lineのテスト」
   * 通知を送信するトークルーム「1:1でLINE Notifyから通知を受け取る」
1. 設定項目C1にそのトークンを入力し、I1に文字型項目(複数行/単一行の両方をテスト)を指定
1. QBPMSで、I1に指定した項目に値を入力して実行すると、LINE Notifyからその値がLINEに送信されること
  * [トークン名] データ項目の値 という形式でLINE が送られてくること
    * 例えば、データ項目の値が「テスト」の場合、以下のような内容が送信されること
      * [lineのテスト1] テスト
  * 1文字、1000文字は問題なく送信できること
    * 全角1000文字送信できること
    * 改行も1文字とカウントされること
  * 0文字、1001文字の場合はエラーを返すこと
    * 自動処理ログに以下のように表示されること
```
0文字の場合、「スクリプトエラーが発生しました。 Message is empty. (#8)」
1001文字の場合、「 スクリプトエラーが発生しました。 Message Length over 1000 (#10)」
```
  * 設定項目C1に不正なトークンを入力した場合、処理失敗すること
    * 自動処理ログに以下のように表示されること
```
{"status":401,"message":"Invalid access token"}
スクリプトエラーが発生しました。 Status Code is not 200.401 (#22)
```

気になること
  * 処理完了の場合も以下のように自動処理ログに表示されます。そういう仕様なのでしょうか？失敗の時もjsonを表示させているようですが、これも仕様でしょうか？処理失敗の場合は形式がjsonでいいのかはさておき、トークンが不正であることはわかりやすいです。
```
処理完了の場合
{"status":200,"message":"ok"}
処理失敗の場合
{"status":401,"message":"Invalid access token"}
スクリプトエラーが発生しました。 Status Code is not 200.401 (#22)
```
ver. 11.6.0 rev. 34992 SaaS Edition

**Comment by R-Matsubayashi** [comment]
jsonをログに出力しているのは仕様ですね。レスポンスの形式が変わっても全て出力できるように、という意図があります。

**Comment by hatanaka-akihiro** [comment]
改良しましょう。

テキストの指定を、プロパティダイアログでの直接指定 (textarea) に変える。
ただしtextarea で EL 式を使えるようにする。
最初にチュートリアルで slack への投稿をしていると思いますが、そこで EL 式を使うサンプルを見ているはずです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

chica-non にテストをしてもらうのは難しい状況です。（別に優先度の高いものがある）

本チケットについても、自分でテストしてもらうことになりますので、テストの前に、まずテストの設計をするようにしてください。

**Comment by tron-kmc** [comment]
設定
C1:単一行テキスト、必須
C2:複数行テキスト、必須、EL式可

必須 → 入力されていない場合アプリがエラーになる。
EL式可→EL式用のUIが表示される。EL式を使ったテキストを送信できる。

実行
[C1:C2]
空白:空白 → アプリエラー
空白:1～1000文字 → アプリエラー
正しい:空白 → アプリエラー
正しい:1～1000文字 → LINE Notifyを通じてトークン発行時に指定したアカウント/グループにメッセージが送信される
正しい:1001文字～  →スクリプトエラー"Message Length over 1000"
間違い:1～1000文字 → スクリプトエラー"Status Code is not 200."
間違い:1001文字～ → スクリプトエラー"Message Length over 1000"

いずれの場合もC1,C2は変化しない。

テストはこれでよいでしょうか？

**Comment by R-Matsubayashi** [comment]
アカウントを間違えていた……上のコメントは私のものです。

**Comment by hatanaka-akihiro** [comment]
まだ I1 が C2 に変化したものがマージされていないですよね．．．

- C1 の「正しい」「間違い」。「正しい」はまあ良いとして、「間違い」はもう少しきちんと定義したほうが良いです。「そもそも入力ミスで間違えている」という場合を指していると思いますが、「かつて使えたトークンだったが、使えなくなった」というパターンはありえないでしょうか。

- C2 については、EL 式を許容するようになったので、EL 式を評価した結果、空になるというパターンがありえます。このパターンは「アプリエラー」にならないです。つまり「空白」「1-1000文字」「1001文字-」という3つの場合分けでは、足りないということです。

- EL 式については、更に EL 式の「評価エラー」がありえます。が、評価エラーになるパターンがややこしいので、省略で構わないです。

**Comment by R-Matsubayashi** [comment]
設定
C1:単一行テキスト、必須
C2:複数行テキスト、必須、EL式可

必須 → 入力されていない場合アプリがエラーになる。
EL式可→EL式用のUIが表示される。EL式を使ったテキストを送信できる。

実行
[C1:C2]
空白:空白 → アプリエラー
空白:1～1000文字 → アプリエラー
有効:空白 → アプリエラー
有効:空白になるEL式→スクリプトエラー"Message is empty."
有効:1～1000文字 → LINE Notifyを通じてトークン発行時に指定したアカウント/グループにメッセージが送信される
有効:1001文字～  →スクリプトエラー"Message Length over 1000"
無効:空白になるEL式→スクリプトエラー"Message is empty."
無効:1～1000文字 → スクリプトエラー"Status Code is not 200."
無効:1001文字～ → スクリプトエラー"Message Length over 1000"

いずれの場合もC1,C2は変化しない。

これでどうでしょうか

>C1 の「正しい」「間違い」。「正しい」はまあ良いとして、「間違い」はもう少しきちんと定義したほうが良いです。「そもそも入力ミスで間違えている」という場合を指していると思いますが、「かつて使えたトークンだったが、使えなくなった」というパターンはありえないでしょうか。

に関しては、いずれの場合もLINE Notifyは単に「無効なトークンである」と認識するようなので、区別の必要はないと考えました。

**Comment by hatanaka-akihiro** [comment]
「EL 式を使用」「EL 式を使用せず」のそれぞれで、「1-1000文字」「1001文字-」の2パターンあります。

- 「有効:1～1000文字」のパターンは、「EL 式を使用」「EL 式を使用せず」の両方でしてください。
- 「有効:1001文字～」「無効:1001文字～」は、片方を「EL 式を使用」、もう片方を「EL 式を使用せず」にするとよいでしょう。

もうちょっとテストケースを減らして良いかなとも思いますが、ま、問題ではありません。
上記の指摘についてテストケースを修正し、これに従ってテストを行ってください。
テスト結果は記録してください。

**Comment by R-Matsubayashi** [comment]
30a414d のテストを行いました。

設定
C1:単一行テキスト、必須
C2:複数行テキスト、必須、EL式可

必須 → 入力されていない場合アプリがエラーになる。
EL式可→EL式用のUIが表示される。EL式を使ったテキストを送信できる。
指定通りの入力窓であること、入力なしではエラーになることを確認

実行
[C1:C2]
空白:空白 → アプリエラー　確認
空白:1～1000文字 → アプリエラー　確認
有効:空白 → アプリエラー　確認
有効:空白になるEL式→スクリプトエラー"Message is empty."　確認
有効:1～1000文字(EL式あり) → LINE Notifyを通じてトークン発行時に指定したアカウント/グループにメッセージが送信される　確認(1文字と1000文字で)
有効:1～1000文字(EL式なし) → LINE Notifyを通じてトークン発行時に指定したアカウント/グループにメッセージが送信される 確認(1文字と1000文字で)
有効:1001文字～(EL式なし)  →スクリプトエラー"Message Length over 1000" 確認(1001字)
無効:空白になるEL式→スクリプトエラー"Message is empty."　確認
無効:1～1000文字 → スクリプトエラー"Status Code is not 200."　確認(1字で)
エラーコード
{"status":401,"message":"Invalid access token"}
スクリプトエラーが発生しました。 Status Code is not 200.401 (#17)　

無効:1001文字～(EL式あり) → スクリプトエラー"Message Length over 1000"確認

いずれの場合もC1,C2は変化しない。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

userCheck.xml と同じく、help-page-url と last-modified のタグを追加してください。
（細かいことは #33 のチケット参照のこと)

help-page-url で指定する URL は以下としてください。
日本語ページの URL ですので、英語ページの URL は類推してください。

https://www.questetra.com/ja/tour/m4/m415/addon-line-push-notify/

**Comment by hatanaka-akihiro** [comment]
なお先の URL ですが、ページ自体は未作成です。

リンクをクリックしても「見つかりません」のエラーになります。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

２つ追加。

- ファイル名を、Line-pushNotify.xml にしてください。
- https://www.questetra.com/tour/m4/m415/check-the-user-is-in-the-organization/ のページにあるような、設定ダイアログの画面キャプチャを取り、このチケットに貼り付けてください。日英両方とも。

**Comment by R-Matsubayashi** [comment]
![en](https://user-images.githubusercontent.com/36219261/39032783-0078b9ae-44aa-11e8-8a3f-f9961afbfb54.png)
![ja](https://user-images.githubusercontent.com/36219261/39032784-00a7f4d0-44aa-11e8-96bd-139d90b0d1f7.png)
トークンは無効なものです。

**Comment by R-Matsubayashi** [comment]
![ja2](https://user-images.githubusercontent.com/36219261/39034335-fdda9562-44b0-11e8-9d77-ffde9dcfbc43.png)
![en2](https://user-images.githubusercontent.com/36219261/39034337-fe772aee-44b0-11e8-837a-4126972d5d2c.png)
こちらもタイトルを変えてやり直しました。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

- 「ファイル名を変更してください」という話でしたが、名前変更前のファイルが残っているようです。
- last-modified についてですが、コミットした日付に自動的に置き換えられるような機能が、github にないでしょうか。subversion には「キーワード置換」という機能がありました。類似の機能があるかどうか、調べてみてください。

**Comment by R-Matsubayashi** [comment]
変更前のファイルは消しましたので、Pull Requestしておきます。

>last-modified についてですが、コミットした日付に自動的に置き換えられるような機能が、github にないでしょうか。subversion には「キーワード置換」という機能がありました。類似の機能があるかどうか、調べてみてください。

以下のサイトを見る限り出来るように思いますが、ちょっとややこしいので今すぐというわけにはちょっといかないですね。
https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%81%AE%E5%B1%9E%E6%80%A7

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

「常に」チケットに紐づけるように、コミットメッセージを残すようにしてください。
チケットに紐づかなければ、コミットメッセージを修正するようにしてください。

last-modified の値を自動的にする件は諦めましょう。
last-modified のタグは、service-task-definition 直下で先頭にもってきてください。

**Comment by hatanaka-akihiro** [comment]
https://www.questetra.com/ja/tour/m4/m415/addon-line-push-notify/

に公開されました。

英語はこれからですが、本チケットはクローズします。
