### ISSUE TITLE
Slack ファイルをアップロードする

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#86]
Bots を使って、ファイルをアップロードする自動工程を作成する。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

そもそもファイルをアップロードすると、Slack ではどのように見えるか、教えてもらえませんか。

**Comment by R-Matsubayashi** [comment]
![36711ad1f9803238ea6aa7940b75eb22](https://user-images.githubusercontent.com/36219261/51818801-85f09c80-2313-11e9-854f-f22ea32f443e.png)
こういう感じです。上がSnippet展開できるもの(テキストなど)、下がそうでないファイルです。

**Comment by hatanaka-akihiro** [comment]
Slack の概念としては、「１ファイルアップロードごとに１コメント」なのでは？

複数のファイルに対して、１つのコメントをつけるという概念がないように思います。

**Comment by hatanaka-akihiro** [comment]
であるなら、

- 全部に同じコメントをつける
- 最初のファイルだけにつける

は、今一つですね。

1. １つのファイルアップロードしかできないようにする
2. 複数ファイルそれぞれに対して、別々のコメントをつけられるようにする
3. 複数ファイルをアップロードできるようにするが、コメントをつける機能は提供しない

のいずれかでしょうか。実装がシンプルな1か3で良いように思います。
3もアリだと思うのは、別にメッセージを投稿するアドオンがあるので。

**Comment by hatanaka-akihiro** [comment]
将来的に、1 を 2 に改良する可能性を考えるなら、コメントは1行に制約しておいた方が良いでしょうか。

3 を 2 に改良する可能性を考えるなら、2 への改良時のことを今から考える必要はないですかね。

**Comment by R-Matsubayashi** [comment]
それでは、3でいきます。1つだけだと、いくつファイルを送ることになるかわからない、という場合に困りそうなので。

**Comment by hatanaka-akihiro** [comment]
3 の仕様だとしても、無制限に何個もファイルをアップロードできないという点に注意してください。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1vgA2O92yWK1tJWjvS4kZPmkQ1txr1JCJ_j_HSE7XKX4/edit?usp=sharing

テスト設計しました。アップロード数の上限についてはhttpClient.getRequestingLimit()で規定していますが、アドオンの場合は10回が上限という認識で合っていますか？

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

テスト設計、ざっと見たところ、問題無さそうです。

つまらない指摘ですが、「未入力」と「未設定」は同じ言葉を使ったほうが良いです。
両方とも、「ワークフローアプリにおける工程の設定として、設定しない」という意味で使っていると思うので。

> アップロード数の上限についてはhttpClient.getRequestingLimit()で規定していますが、アドオンの場合は10回が上限という認識で合っていますか？

はい。あっています。スクリプト内における、HTTP リクエスト数の上限が 10 です。
「公式アイテム」として動作する場合は違うので、「QBPMS の上限に従う」とか、なにか書いておくのが良いですね。

**Comment by R-Matsubayashi** [comment]
テストしました。

**Comment by R-Matsubayashi** [comment]
画面キャプチャです。
![1299de1a7cb511de58da029f100f25bd](https://user-images.githubusercontent.com/36219261/52194201-358ab900-2896-11e9-8f7d-9ee671197024.png)
![7b5125225fd6baaa54add9dcec55ad3d](https://user-images.githubusercontent.com/36219261/52194202-36234f80-2896-11e9-9d1a-0cd2ca1ddd50.png)

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

- メッセージ投稿 Bots 版と同じく、タイトルに (Bots) を入れるように。
- C2 「Slack チャンネル ID」で良いです。メッセージ投稿のアドオンにあわせたと思いますが。
- "Upload a file to Slack with Bots" "Upload files to Slack with Bots" にしましょう。せっかく、複数ファイルのアップロードに対応したはずなので。

設定画面については、以上です。

**Comment by R-Matsubayashi** [comment]
>upload() 関数の中、ファイルアップロードに失敗して例外をスローするところ。responseTxt に、アップロードしようとしたファイルが解る情報は含まれるのだろうか？通知メールにおいては、スローされた例外の内容が、そのまま記載されるので。

レスポンスにはないですね。ファイル名を出すタイミングを変えます。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1vgA2O92yWK1tJWjvS4kZPmkQ1txr1JCJ_j_HSE7XKX4/edit?usp=sharing
直したので、テストしました。

**Comment by R-Matsubayashi** [comment]
テスト中にわかったことですが、写真(1枚は3～4MBくらい)をアップロードしようとすると、3枚目で

>スクリプトエラーが発生しました。 java.util.concurrent.TimeoutException

になって終了します。
あるいは重いファイル(10MBとか20MBとか)を複数アップロードする場合でも同じことになりますが、常に同じ条件で起こるわけではないようです。

**Comment by hatanaka-akihiro** [comment]
- スクリプトの実行時間
- HTTP リクエストの送信時間

には、いずれも制限がかかっています。

事前にそれを超えるかどうか知るのは難しいので、「時によって、結果が変わる」のは仕方がないと考えています。

**Comment by R-Matsubayashi** [comment]
![3cbeda29375f73119afc8f3948730f2d](https://user-images.githubusercontent.com/36219261/52467187-f88d3200-2bc7-11e9-9300-16f31aa5fb1d.png)
![60518eb3e5a8dafd14fbc8d30e123c4b](https://user-images.githubusercontent.com/36219261/52467189-f925c880-2bc7-11e9-8577-4ea8344f6c7b.png)
新しいキャプチャです。

**Comment by hatanaka-akihiro** [comment]
@R-Matsubayashi 

Bot が join していないチャンネルに、ファイルアップロードできる点が引っかかります。

メッセージ投稿と仕様をあわせられないのでしょうか？

Slack のバグ？

**Comment by hatanaka-akihiro** [comment]
```
if (file == null){
    engine.log ("No File to upload");
}else{
```

ここ。if ... else ... 文よりも、return で抜けた方が、解りやすいです。

return を使えるように、スクリプトの処理全体を関数 (main()) で定義するようにしている。

**Comment by R-Matsubayashi** [comment]
>Bot が join していないチャンネルに、ファイルアップロードできる点が引っかかります。
>メッセージ投稿と仕様をあわせられないのでしょうか？

ドキュメントを読む限り、そのあたりに関する記述が全くないので、できないということになると思います。
エラー一覧にもそもそも「指定したチャンネルにjoinしていない」というものがありません(メッセージ投稿のほうにはありました)。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1vgA2O92yWK1tJWjvS4kZPmkQ1txr1JCJ_j_HSE7XKX4/edit?usp=sharing
新バージョンでテストしました。
2つ以上のチャンネルに同時にアップロードする部分がテストできていなかったので追加しました。

**Comment by hatanaka-akihiro** [comment]
メッセージ投稿は、複数チャンネルに投稿可能ですか？

**Comment by hatanaka-akihiro** [comment]
利用シーンが思い当たらないので、現時点で、複数チャンネルに対応しなくて良いです。

**Comment by R-Matsubayashi** [comment]
>利用シーンが思い当たらないので、現時点で、複数チャンネルに対応しなくて良いです。

configから説明を消すということでいいですか(複数チャンネル対応自体はデフォルトでなされています)。

**Comment by hatanaka-akihiro** [comment]
> 複数チャンネル対応自体はデフォルトでなされています

なるほど。こういう大事なことは、最初の質問時に説明してもらえるとありがたいです。

ところで、メッセージ投稿の方も、同じ話ですか？
ファイルアップロードだけの話ですか？

**Comment by R-Matsubayashi** [comment]
メッセージのほうは違うようです。

**Comment by hatanaka-akihiro** [comment]
もしかしたら、ファイル容量節約のため、ファイルアップロードは複数チャンネルに対応しているのかもしれないですね。

が、類似カテゴリのアイテムは、同じ仕様の方が解りやすいので、同じ仕様にしたいです。

**Comment by hatanaka-akihiro** [comment]
チャンネル名に指定可能な文字は、アスキー文字に限れば、英小文字／数字／ハイフン／アンダーバーのようですが、それら以外があればエラーとしてはどうでしょうか。

**Comment by hatanaka-akihiro** [comment]
> チャンネル名に指定可能な文字は、アスキー文字に限れば、英小文字／数字／ハイフン／アンダーバーのようですが、それら以外があればエラーとしてはどうでしょうか。

現時点でこのチェックの仕組みは、入れなくて良いです。
(想定しないけど、チェックは入れない)

**Comment by R-Matsubayashi** [comment]
>チャンネル名に指定可能な文字は、アスキー文字に限れば、英小文字／数字／ハイフン／アンダーバーのようですが、それら以外があればエラーとしてはどうでしょうか。

「そんなチャンネルはない」ということになります。

**Comment by hatanaka-akihiro** [comment]
以降は別システムで、チケットを管理するため。
