### ISSUE TITLE
「Google Sheets 2列データの一括取得」の改良

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#88]
Google Sheets 2列データの一括取得
https://support.questetra.com/ja/addons/googlesheets-getidslabels

を改良する。

- A: OAuth2通信許可設定名 `form-type="OAUTH2"` に
- B: Spreadsheet ID `form-type="TEXTFIELD"` に
- C: Sheet タイトル `form-type="TEXTFIELD"` に
- H: 廃止。スクリプトのロギングの機能を使うように。

**Comment by hatanaka-akihiro** [comment]
```data.get(dataIdE)``` など、スクリプトの書き方として古いところも、改良対象。

**Comment by R-Matsubayashi** [comment]
元のコードでは200以外のステータスコードが返ってきてもエラーにはなりませんが、エラーにすべきですか？

**Comment by hatanaka-akihiro** [comment]
> 元のコードでは200以外のステータスコードが返ってきてもエラーにはなりませんが、エラーにすべきですか？

200以外のステータスコードでも、意図した処理が完遂できるなら、そのまま処理を進めるようにプログラムを構成すると良いでしょう。

そうでないなら、サービスタスクは異常終了となるように、例外をスローした方が良いです。

**Comment by R-Matsubayashi** [comment]
今テストを作っていますが、このままテストに進んでいいでしょうか？
(他に足したり引いたりする機能がないか、ということです)

**Comment by hatanaka-akihiro** [comment]
> 今テストを作っていますが、このままテストに進んでいいでしょうか？

「テスト作成にすすんで良いか」という意味ですかね？

一部、仕様をこのままで行くか悩んでいるところはありますが、テスト作成に進んでください。

あとテストを実施する前に、コードを見たいと考えています。テスト実施前に、Pull リクエストを行ってください。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1lF5VV4x9N9HGuucc6q_320iwkDi_OkWhoq1gU1xD7dA/edit?usp=sharing

テストです。

**Comment by hatanaka-akihiro** [comment]
> C1: OAuth2通信許可設定名 (←［OAuth 2.0 設定］)

form-type="STRING" の名残りで、名前を変えないのは良くないです。


> C2: Spreadsheet ID（存在しない場合、エラー）

「（存在しない場合、エラー）」の部分、削除してください。
これまでのアドオンでしていないので。
QBPMS 組み込み済みアイテム含めて、同じようなラベルになっているか、気にしてください。

I1 と I2 も form-type="STRING" に変更してください。

**Comment by hatanaka-akihiro** [comment]
"I1" - "I4" の設定記号を "C4" - "C7" に変更して下さい。

特に I と C の判定が難しいので、全て C に統一します。

ちなみに I3 と I4 は Output なので、分類するなら、O1 O2 です。

**Comment by R-Matsubayashi** [comment]
>I1 と I2 も form-type="STRING" に変更してください。

form-type="TEXTFIELD"にするということですか？それともselect-data-type="STRING"ということですか？

**Comment by hatanaka-akihiro** [comment]
ごめんごめん。

form-type="TEXTFIELD" です。簡単にする。

**Comment by hatanaka-akihiro** [comment]
テスト設計について。

「選択肢IDの領域情報」「選択肢ラベルの領域情報」で、「途中に空セルあり」をスクリプトエラーとしているのは、元のスクリプトの仕様？

かなり「選択肢データの取得」に寄せた仕様で、「2列データの一括取得」という名前に似つかわしくないなと思ったので。ここまで寄せるなら、「選択肢データの一括取得」にした方が良いと思った。

**Comment by R-Matsubayashi** [comment]
>「選択肢IDの領域情報」「選択肢ラベルの領域情報」で、「途中に空セルあり」をスクリプトエラーとしているのは、元のスクリプトの仕様？

そういうふうに書いてあるものだからてっきりAPI側にそういう機能があるのだと思いこんでいましたが、見てみたところスクリプトにもAPIにもそんな機能はありませんでした。単に「後段の利用を考えるとそうあるべき」という話のようですね。「I1と数が違う」にしてもそうです。

>かなり「選択肢データの取得」に寄せた仕様で、「2列データの一括取得」という名前に似つかわしくないなと思ったので。

そもそも「選択肢IDの領域情報」「選択肢ラベルの領域情報」というlabel自体変えたほうがいいでしょうか？

**Comment by hatanaka-akihiro** [comment]
> 見てみたところスクリプトにもAPIにもそんな機能はありませんでした。単に「後段の利用を考えるとそうあるべき」という話のようですね。「I1と数が違う」にしてもそうです。

なんと！！！

> そもそも「選択肢IDの領域情報」「選択肢ラベルの領域情報」というlabel自体変えたほうがいいでしょうか？

「指定範囲のデータを取得する」汎用的なアイテムとするか、「選択肢データの取得」に特化したアイテムにするか、分かれ目だと思います。汎用的なアイテムとするなら、「2列」にする理由もありません。このアイテムは「選択肢データの取得」に特化したアイテムにする方が、適当だと思います。

ですので、設定項目のラベルは変更しなくて良いです。(アイテムの名前は変更したほうが良いです)

また「途中に空セルあり」「数が違う」というものについても、バリデーションエラーとするようにできますか？「ID の重複」もチェックしたいところです。

**Comment by R-Matsubayashi** [comment]
間違えてました。「I1と数が違う」のほうはデータ項目に書き出す文を作るためのfor文が「選択肢IDの領域情報」の数だけ回るので、数が違うと後ろのほうが書き出されなかったり逆にオーバーしたりしますね。

**Comment by tron-kmc** [comment]
>また「途中に空セルあり」「数が違う」というものについても、バリデーションエラーとするようにできますか？「ID の重複」もチェックしたいところです。

スクリプトエラーでいいですよね？

**Comment by R-Matsubayashi** [comment]
>また「途中に空セルあり」「数が違う」というものについても、バリデーションエラーとするようにできますか？「ID の重複」もチェックしたいところです。

スクリプトエラーということでいいですよね？

**Comment by R-Matsubayashi** [comment]
>また「途中に空セルあり」「数が違う」というものについても、バリデーションエラーとするようにできますか？「ID の重複」もチェックしたいところです。

対応しました。

https://docs.google.com/spreadsheets/d/1lF5VV4x9N9HGuucc6q_320iwkDi_OkWhoq1gU1xD7dA/edit?usp=sharing

テストも作り直しました。

**Comment by R-Matsubayashi** [comment]
(他にできることもなかったので)上のものでテストをしました。

**Comment by hatanaka-akihiro** [comment]
別システムでチケットを管理するので、クローズする。
