### ISSUE TITLE
「Google Sheets 行追加」を改良する

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#89]
Google Sheets 行追加
https://support.questetra.com/ja/addons/googlesheets-appendcells

を改良する。

- V: OAuth2通信許可の設定名を `form-type="OAUTH""` に
- W: Spreadsheet ID を `form-type="TExT=FIELD"` に
- W: Sheet GID を 'form-type="TEXT-FIELD"` に。
 - 「Google Sheets 2列データの一括取得」と仕様が揺らいでいるので、シート名にできないか
- Y: 通信ログを配信。スクリプトのロギング機能を使うように。
- A-J: いずれも 'form-type="TEXT-FIELD"` で「EL 式可」に。

**Comment by hatanaka-akihiro** [comment]
```data.get(dataIdE)``` など、スクリプトの書き方として古いところも、改良対象。

**Comment by R-Matsubayashi** [comment]
>「Google Sheets 2列データの一括取得」と仕様が揺らいでいるので、シート名にできないか

Spreadsheet IDを送るとシートの情報が返ってくるメソッドはあるので、それを使って情報を取ってきて、そこから指定した名前のシートを探して、GIDを取得する……というやり方ならできそうです。

**Comment by R-Matsubayashi** [comment]
とりあえず、名前で追加できるようになったはずです。

**Comment by R-Matsubayashi** [comment]
今テストを作っていますが、このままテストに進んでいいでしょうか？

**Comment by hatanaka-akihiro** [comment]
> 今テストを作っていますが、このままテストに進んでいいでしょうか？

「テスト作成にすすんで良いか」という意味ですかね？

一部、仕様をこのままで行くか悩んでいるところはありますが、テスト作成に進んでください。

あとテストを実施する前に、コードを見たいと考えています。テスト実施前に、Pull リクエストを行ってください。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1CAEVYAGucisROiRbzBImp6heT27sGB2kv4fnM1lJPSE/edit?usp=sharing

テストです。

**Comment by R-Matsubayashi** [comment]
@hatanaka-akihiro どうでしょうか？

**Comment by hatanaka-akihiro** [comment]
C4, C5 ではなく、CA, CB とか C-A, C-B の方が良いかも。A 列, B 列だから。

設定記号、連番になっていることに、こだわらなくて良いです。

**Comment by hatanaka-akihiro** [comment]
テストの記載の仕方として、まず

- C1: OAuth2通信許可の設定名
- C2: Spreadsheet ID
- C3: Sheet タイトル

のエラーの集中して、列挙したほうが良いです。

C4 から C13 は類似の設定項目なので、うまく省略しているのは良いと思います。

(1) 設定している
(2) 未設定
(3) EL 式の指摘先が空 (「EL 式を評価した結果が空」の方が良いと思います)

と読めば良いと思いましたが、「C4 が (1) でほかが (2) のテストケース」が「追加されない」のはおかしいです。すべて (2) の間違いだと思います。

テストケースとして、「全て (2) or (3)」のパターンは必要です。

**Comment by hatanaka-akihiro** [comment]
(4) 入力規則に反する
(5) 文字数が 5 万文字を超える

は、セルで受け付けるデータに関する制約だと思います。
「入力規則」がよく解らなかったので、詳しく教えてください。

**Comment by hatanaka-akihiro** [comment]
(6) セル数が 200 万を超える

「1シート内のセル数 200 万」という制約があるのでしょうか。
それとも、「1 Spreadsheet ファイル内のセル数 200万」？

いずれにせよ、C2 か C3 のテストパターンとして列挙したほうが良いと思います。

**Comment by hatanaka-akihiro** [comment]
もう１つ。
Spreadsheet にとって、「追加されない」と「空文字データが追加される」は区別されるのでしょうか？

**Comment by R-Matsubayashi** [comment]
>「C4 が (1) でほかが (2) のテストケース」が「追加されない」のはおかしいです。すべて (2) の間違いだと思います。

確かにそのとおりです。

>「1シート内のセル数 200 万」という制約があるのでしょうか。
それとも、「1 Spreadsheet ファイル内のセル数 200万」？

ファイル内ですね。

>「入力規則」がよく解らなかったので、詳しく教えてください。

入力内容を「この範囲にある数字」「文字列」「この範囲のセルの数値」といった形で指定して、それ以外が入力された場合に警告を出したり入力を拒否したりするようにできます。

>Spreadsheet にとって、「追加されない」と「空文字データが追加される」は区別されるのでしょうか？

そもそもスクリプトで「何も設定されていない」=「空文字を送る」なので、向こうで区別されることはないかと。

**Comment by hatanaka-akihiro** [comment]
> > 「入力規則」がよく解らなかったので、詳しく教えてください。
> 
> 入力内容を「この範囲にある数字」「文字列」「この範囲のセルの数値」といった形で指定して、それ以外が入力された場合に警告を出したり入力を拒否したりするようにできます。

なるほど。Spreadsheet 側に、そういう機能があるのですね。


ところで、「空文字」の件に関連して質問。
シートが J 列まで無い場合、例えば A, B, C の3列しかない場合、J 列まで含むデータを追加しようとすると、どうなるのでしょうか？いきなり D 列から J 列が登場するのでしょうか？

**Comment by R-Matsubayashi** [comment]
>シートが J 列まで無い場合、例えば A, B, C の3列しかない場合、J 列まで含むデータを追加しようとすると、どうなるのでしょうか？いきなり D 列から J 列が登場するのでしょうか？

今試してみたところ、400エラーになりました。既存の列にも追加はされませんでした。

**Comment by R-Matsubayashi** [comment]
さらに言うと、D-J列は空にしてもエラーになりました。

**Comment by hatanaka-akihiro** [comment]
つまりこのアイテムは、「今のところ」 J 列までないシートを対象にできないわけですね。

D-J 列の設定が空なら (EL 式もない)、A,B,C の3列しかデータを追加しないという仕様も考えられますが、今のところ、プログラムの側で「設定が空 (EL 式もない)」のと「EL 式の評価結果が空」というのを区別できないですよね．．．

将来的な課題として、今は諦めるしかないか。

**Comment by R-Matsubayashi** [comment]
試しに空文字の列についてはnullを送るようにしてみたら、C列までのものに正しく追加できました。

**Comment by hatanaka-akihiro** [comment]
> 試しに空文字の列についてはnullを送るようにしてみたら、C列までのものに正しく追加できました。

なるほど。

「EL 式の評価結果が空」の場合に、「null を送る / データを追加しない」が適当かどうか、ですよね。

**Comment by R-Matsubayashi** [comment]
「EL 式の評価結果が空の場合にデータを追加しない」ことの問題点がわからないのですが、何か問題があるのでしょうか？

**Comment by hatanaka-akihiro** [comment]
> 「EL 式の評価結果が空の場合にデータを追加しない」ことの問題点がわからないのですが、何か問題があるのでしょうか？

ワークフローの開発者の意志としては、設定が空ではないので、データ追加する意思があると考えられるからです。設定が空の場合は、「空文字列を追加する意志がある」とも考えられますが、基本的には、「追加する意志がない」と考える方が適当でしょう。

これに関連して１つ質問。
Spreadsheet は、全列空の行を追加できるのでしょうか？

**Comment by R-Matsubayashi** [comment]
>Spreadsheet は、全列空の行を追加できるのでしょうか？

できます(できました)。

**Comment by hatanaka-akihiro** [comment]
以降は別システムで、チケットを管理するため。
