### ISSUE TITLE
「ファイルダウンロード」を改良する

### ISSUE THREAD

**Issue by hatanaka-akihiro** [Questetra/Addon-XML#90]
ファイルダウンロード
https://support.questetra.com/ja/addons/any-website-file-download/

を改良する。

- A: File URL を `form-type="TEXTFIELD"` で EL 式可に。
- C: Content-Type 廃止
- D: バイト数 廃止

**Comment by hatanaka-akihiro** [comment]
気になるのは、ファイル名をダウンロード URL のパスから自動取得している部分。

% エンコーディングされている場合等に、対応しているのだろうか。
対応していない場合、要対応。

難しい場合は、Bx 必須に変える。

**Comment by R-Matsubayashi** [comment]
パーセントエンコーディング対応、難しいです。Javascriptにデコードする関数はあるのですが、それでデコードできるかはものによる(エンコードされた環境次第)ので。
Bx必須にしようかと思います。

**Comment by R-Matsubayashi** [comment]
そういえば、configのラベルにある(更新)って何なんでしょうか。外してもいいですか？

**Comment by hatanaka-akihiro** [comment]
> Bx必須にしようかと思います。
了解しました。

> configのラベルにある(更新)って何なんでしょうか。
指定のデータ項目の値が「更新される」ということを意味していたはずです。
このアイテムも QBPMS に組み込むつもりですが、他のアイテムとの統一感もあるので、外してください。

**Comment by R-Matsubayashi** [comment]
大きいファイルをダウンロードするとjava.lang.OutOfMemoryError: Java heap spaceが出るんですが、ヒープメモリって最大何MBですか？

**Comment by hatanaka-akihiro** [comment]
> 大きいファイルをダウンロードするとjava.lang.OutOfMemoryError: Java heap spaceが出るんですが、ヒープメモリって最大何MBですか？

環境によります。
お試しの環境は小さく、有償の環境は大きいです。
具体的な数値は公開していません。

**Comment by R-Matsubayashi** [comment]
ではテストには組み込めませんね。

**Comment by hatanaka-akihiro** [comment]
ちなみに、ダウンロードしたファイルのサイズは？

**Comment by R-Matsubayashi** [comment]
93.2MBですね。ファイル型データ項目がQBPMS上では100MBまでしかできないので、このアドオンではどうなるかと思ってやっていました。

**Comment by hatanaka-akihiro** [comment]
いい着眼点ですね。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1kbav56HMTSrYkqwqhdQOGBz9yRzal9cASdbXhrbVChg/edit?usp=sharing

テスト設計しました。実際には通信時のエラー回りはまだ書けていませんが。

**Comment by R-Matsubayashi** [comment]
テストしたいのですが、上のもので大丈夫でしょうか。

**Comment by hatanaka-akihiro** [comment]
通信エラーになるパターンは、

- 正常応答が返ってこない
- 接続できない

の２分類の方が適当だと思いました。

「存在しない URL」が接続できるとも限らないですし、アクセス権限がない場合に 403 応答が返ってくるとも限らない。

応答が返ってきて 200 でないパターンには、リダイレクトとかも考えられますが、QBPMS の通信機能そのもののテストになってくるんどえ、そこまではしなくて良いかな。

**Comment by hatanaka-akihiro** [comment]
ファイル名には 200 文字制限がありますね。

200 文字制限はシステム制限で、それを考慮するならファイルサイズにも別の制限 (「システム設定 -> ファイルリポジトリ」で確認可能) があります。

ファイルリポジトリの容量制限は確認が大変なので、省略で良いと考えます。

**Comment by hatanaka-akihiro** [comment]
指摘ふまえてテストを改良した上で、テストを進めてください。

**Comment by R-Matsubayashi** [comment]
>通信エラーになるパターンは、
>* 正常応答が返ってこない
>* 接続できない
>の２分類の方が適当だと思いました。

これらは実際テストするときはどのようなURLを使えばよいでしょうか？
404エラーは前者に入るということでいいですか？

**Comment by hatanaka-akihiro** [comment]
「正常応答が返ってこない」というのは、「接続できたけどサーバから 200 が返ってこない」というパターンです。404 エラーも 403 エラーも、こちらに入ります。

> これらは実際テストするときはどのようなURLを使えばよいでしょうか？

逆に質問しますが、404 / 403 エラーはどういう URL でテストするつもりだったのでしょうか？

あと DNS で名前解決できないような URL なら、接続できないです。

**Comment by R-Matsubayashi** [comment]
接続できる/できないというのはサーバーレベルの話なわけですね。わかりました。

>逆に質問しますが、404 / 403 エラーはどういう URL でテストするつもりだったのでしょうか？

ブラウザでアクセスしてそれらのエラーが出るURLで、というつもりでした。

**Comment by hatanaka-akihiro** [comment]
> ブラウザでアクセスしてそれらのエラーが出るURLで、というつもりでした

それで良いと思います。


> 接続できる/できないというのはサーバーレベルの話なわけですね。わかりました。

ごめん。理解できませんでした。
「サーバーレベル」とはどういう意味ですか？
何と勘違いしたのでしょうか？

**Comment by R-Matsubayashi** [comment]
「接続できない」は「サーバーに接続できない」ということか、ということです。
「個々のページにアクセスできる/できない」というような意味かと思っていました。

**Comment by hatanaka-akihiro** [comment]
理解しました。

**Comment by R-Matsubayashi** [comment]
https://docs.google.com/spreadsheets/d/1kbav56HMTSrYkqwqhdQOGBz9yRzal9cASdbXhrbVChg/edit?usp=sharing

テストしました。

**Comment by hatanaka-akihiro** [comment]
以降は別システムで、チケットを管理するため。
